#if os(macOS)
import BoltzMLX
import Foundation
import XCTest
@testable import RayMol

/// Measures peak MLX memory over a (tokens × MSA depth) grid, and prints it as the
/// table `PredictSizeGuardTests.measured` is written from.
///
/// This exists because ``PredictSizeGuard`` may not be extended analytically. It has run
/// optimistic twice, both times by fitting a curve past its own data, and the constants
/// it ships with were fitted to runs with **no alignment at all** — depth is a dimension
/// it did not model. An MSA term guessed from the shape of the tensors would be the same
/// mistake a third time, so the term is fitted to what this prints and to nothing else.
///
/// Gated, like `DesignInferenceSmokeTests`: each point is a full prediction at the
/// shipped operating point (recycling 3 / 200 diffusion steps), so the grid is tens of
/// minutes, and the normal suite must not block on it.
///
///     cd swiftui && RAYMOL_PREDICT_MSA_SWEEP=1 xcodebuild test \
///       -project PyMOLViewer.xcodeproj -scheme UnitTests_macOS \
///       -destination 'platform=macOS,arch=arm64' -configuration Release \
///       -skipPackagePluginValidation -skipMacroValidation \
///       -only-testing:PyMOLViewerTests/PredictMSAMemorySweepTests
///
/// **The alignments are synthetic, and that is sound here.** Peak memory is decided by
/// the SHAPES of the MSA tensors — depth × tokens — not by what the rows contain, so
/// rows generated by mutating the query measure the same allocation a real search would.
/// It would be unsound for anything about quality, which this does not measure. The
/// alternative — a real a3m of each required depth — would tie the numbers to files that
/// are not in the repo, which is precisely the trap the ticket flags about boltz-mlx's
/// own parity tests.
final class PredictMSAMemorySweepTests: XCTestCase {

    /// Residue counts to sweep. Small and mid: the grid has to fit in the time budget,
    /// and the honest consequence is that the depth ceiling lands where the data stops.
    private static let tokenCounts = [115, 250, 384]

    /// Alignment depths, INCLUDING 1 — the depth-1 row is the control that ties this
    /// sweep back to the existing no-MSA table. If it does not reproduce those numbers,
    /// the harness is measuring something other than what the app runs.
    private static let depths = [1, 64, 256, 1024]

    /// Where `WeightCache` extracts the shipped bundle: <root>/<id>/<version>.
    private static var weightsDirectory: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/RayMol/weights")
            .appendingPathComponent("boltz2-mlx-int8/v1")
    }

    // MARK: - Fixtures

    /// A pseudo-random but DETERMINISTIC canonical-20 sequence of `length` residues.
    ///
    /// Deterministic so a rerun measures the same input; the composition is otherwise
    /// irrelevant to allocation. Seeded splitmix64 rather than `Int.random` so the table
    /// can be reproduced from this file alone.
    static func sequence(length: Int, seed: UInt64 = 0x9E37_79B9_7F4A_7C15) -> String {
        let alphabet = Array("ACDEFGHIKLMNPQRSTVWY")
        var state = seed
        return String((0 ..< length).map { _ in
            state &+= 0x9E37_79B9_7F4A_7C15
            var z = state
            z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
            z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
            z ^= (z >> 31)
            return alphabet[Int(z % UInt64(alphabet.count))]
        })
    }

    /// An a3m whose query is `query` and which has `depth` DISTINCT rows.
    ///
    /// Distinct matters: `MSAAlignment.a3m` deduplicates on the gap-stripped, uppercased
    /// sequence before it counts, so rows that collided would silently measure a
    /// shallower alignment than the one asked for. Every row therefore carries a
    /// substitution pattern unique to its index, and the test asserts the depth it got.
    static func a3m(query: String, depth: Int) -> String {
        let residues = Array(query)
        let alphabet = Array("ACDEFGHIKLMNPQRSTVWY")
        var lines = [">query", query]
        for row in 1 ..< max(depth, 1) {
            var mutated = residues
            // Two positions per row, driven by the row index, so no two rows agree.
            for offset in 0 ..< 2 {
                let position = (row &* 2 &+ offset) % residues.count
                let shift = 1 + ((row / residues.count) + offset) % (alphabet.count - 1)
                let current = alphabet.firstIndex(of: mutated[position]) ?? 0
                mutated[position] = alphabet[(current + shift) % alphabet.count]
            }
            lines.append(">homolog_\(row)")
            lines.append(String(mutated))
        }
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - The sweep

    func testMeasurePeakMemoryOverTokensAndDepth() throws {
        try XCTSkipUnless(
            ProcessInfo.processInfo.environment["RAYMOL_PREDICT_MSA_SWEEP"] == "1",
            "Memory sweep; set RAYMOL_PREDICT_MSA_SWEEP=1 to enable (runs real "
            + "predictions, tens of minutes).")
        let directory = Self.weightsDirectory
        try XCTSkipUnless(
            FileManager.default.fileExists(atPath: directory.path),
            "boltz2 weights are not cached at \(directory.path); run "
            + "`predict_weights boltz2, download=1` first.")

        // Exactly what BoltzJobManager does, so the numbers describe the app's runtime
        // and not this test's. Both lines matter: the cache limit changes what MLX holds
        // between allocations, and `.desktop` is the limit set the app runs under.
        BoltzRuntime.configureOnce()
        let predictor = try BoltzRuntime.withMLXErrorsAsThrows {
            try BoltzPredictor(
                modelDirectory: directory,
                memoryPlanner: MemoryPlanner(limits: .desktop,
                                             cacheLimit: MLXRuntime.activeCacheLimitBytes))
        }

        var options = BoltzPredictionOptions()
        options.recyclingSteps = 3
        options.diffusionSteps = 200
        options.seed = 0

        print("SWEEP,tokens,depth,peak_bytes,peak_gb,seconds")
        // Cheapest first, so a run that has to be cut short still leaves a usable table
        // and the point it died on is the expensive corner rather than a random cell.
        for tokens in Self.tokenCounts {
            let query = Self.sequence(length: tokens)
            for depth in Self.depths {
                let alignment = try MSAAlignment.a3m(Self.a3m(query: query, depth: depth),
                                                     maximumSequences: depth,
                                                     taxonomy: nil)
                XCTAssertEqual(alignment.depth, depth,
                               "the fixture deduplicated: depth \(depth) at \(tokens) "
                               + "tokens measured \(alignment.depth) rows")
                XCTAssertEqual(alignment.queryLength, tokens)

                let canonical = try CanonicalStructure.fromSequences([("A", query)])
                let features = try BoltzFeaturizer().featurize(canonical,
                                                               alignments: ["A": alignment])

                Self.awaitSync { await predictor.resetPeakMemory() }
                let started = Date()
                _ = try BoltzRuntime.withMLXErrorsAsThrows {
                    try Self.awaitSyncThrowing {
                        try await predictor.predictScored(featurized: features,
                                                          options: options)
                    }
                }
                let seconds = Date().timeIntervalSince(started)
                let peak = Self.awaitSyncValue { await predictor.memorySnapshot().peakMemory }
                // One line per point, machine-readable, flushed as it goes: a sweep that
                // is killed part way through must still have published what it measured.
                // %ld, not %d: peak is an Int and every interesting value here is
                // above 2^31, which %d truncates to a negative number.
                print(String(format: "SWEEP,%ld,%ld,%ld,%.2f,%.1f",
                             tokens, depth, peak, Double(peak) / 1e9, seconds))
                fflush(stdout)
                BoltzRuntime.configureOnce()
            }
        }
    }

    // MARK: - async bridging, as BoltzJobManager does it

    private static func awaitSync(_ body: @escaping () async -> Void) {
        let done = DispatchSemaphore(value: 0)
        Task { await body(); done.signal() }
        done.wait()
    }

    private static func awaitSyncValue<T>(_ body: @escaping () async -> T) -> T {
        let done = DispatchSemaphore(value: 0)
        var out: T!
        Task { out = await body(); done.signal() }
        done.wait()
        return out
    }

    private static func awaitSyncThrowing<T>(_ body: @escaping () async throws -> T) throws -> T {
        let done = DispatchSemaphore(value: 0)
        var outcome: Result<T, Error>!
        Task {
            do { outcome = .success(try await body()) } catch { outcome = .failure(error) }
            done.signal()
        }
        done.wait()
        return try outcome.get()
    }
}
#endif
