#if os(macOS)
import BoltzMLX
import Foundation
import XCTest
@testable import RayMol

/// Measures peak MLX memory over a (tokens × MSA depth) grid, and prints it as the
/// table `PredictSizeGuardTests.measured` is written from.
///
/// This exists because ``PredictSizeGuard`` may not be extended analytically. It has run
/// optimistic twice, both times by fitting a curve past its own data, and the constants
/// it ships with were fitted to runs with **no alignment at all** — depth is a dimension
/// it did not model. An MSA term guessed from the shape of the tensors would be the same
/// mistake a third time, so the term is fitted to what this prints and to nothing else.
///
/// Gated, like `DesignInferenceSmokeTests`: each point is a full prediction at the
/// shipped operating point (recycling 3 / 200 diffusion steps), so the grid is tens of
/// minutes, and the normal suite must not block on it.
///
///     cd swiftui && RAYMOL_PREDICT_MSA_SWEEP=1 xcodebuild test \
///       -project PyMOLViewer.xcodeproj -scheme UnitTests_macOS \
///       -destination 'platform=macOS,arch=arm64' -configuration Release \
///       -skipPackagePluginValidation -skipMacroValidation \
///       -only-testing:PyMOLViewerTests/PredictMSAMemorySweepTests
///
/// **The alignments are synthetic, and that is sound here.** Peak memory is decided by
/// the SHAPES of the MSA tensors — depth × tokens — not by what the rows contain, so
/// rows generated by mutating the query measure the same allocation a real search would.
/// It would be unsound for anything about quality, which this does not measure. The
/// alternative — a real a3m of each required depth — would tie the numbers to files that
/// are not in the repo, which is precisely the trap the ticket flags about boltz-mlx's
/// own parity tests.
final class PredictMSAMemorySweepTests: XCTestCase {

    /// Residue counts to sweep. Small and mid: the grid has to fit in the time budget,
    /// and the honest consequence is that the depth ceiling lands where the data stops.
    private static let tokenCounts = [115, 250, 384]

    /// Alignment depths, INCLUDING 1 — the depth-1 row is the control that ties this
    /// sweep back to the existing no-MSA table. If it does not reproduce those numbers,
    /// the harness is measuring something other than what the app runs. (It does: 115
    /// tokens at depth 1 measured 2.12 GB against that table's 1.76 at 100 and 2.90 at
    /// 150, and 250 tokens measured 3.88 against its 3.85.)
    ///
    /// Up to upstream's own cap, because depth turned out to be nearly free in TIME —
    /// 115 tokens ran 21 s at depth 1 and 21 s at depth 1024 — so the grid can reach
    /// the ceiling instead of stopping short of it and refusing everything above.
    private static let depths = [1, 64, 256, 1024, 4096, 16384]

    /// Where `WeightCache` extracts the shipped bundle: <root>/<id>/<version>.
    private static var weightsDirectory: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/RayMol/weights")
            .appendingPathComponent("boltz2-mlx-int8/v1")
    }

    // MARK: - Fixtures

    /// A pseudo-random but DETERMINISTIC canonical-20 sequence of `length` residues.
    ///
    /// Deterministic so a rerun measures the same input; the composition is otherwise
    /// irrelevant to allocation. Seeded splitmix64 rather than `Int.random` so the table
    /// can be reproduced from this file alone.
    static func sequence(length: Int, seed: UInt64 = 0x9E37_79B9_7F4A_7C15) -> String {
        let alphabet = Array("ACDEFGHIKLMNPQRSTVWY")
        var state = seed
        return String((0 ..< length).map { _ in
            state &+= 0x9E37_79B9_7F4A_7C15
            var z = state
            z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
            z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
            z ^= (z >> 31)
            return alphabet[Int(z % UInt64(alphabet.count))]
        })
    }

    /// An a3m whose query is `query` and which has exactly `depth` DISTINCT rows.
    ///
    /// Distinctness is the whole difficulty. `MSAAlignment.a3m` deduplicates on the
    /// gap-stripped, uppercased sequence BEFORE it counts, so colliding rows do not
    /// fail — they silently measure a shallower alignment than the one asked for. A
    /// first version of this mutated positions `2r, 2r+1 (mod length)` with a shift
    /// derived from `r / length`, which is injective at 115 residues and NOT at 250,
    /// where rows r and r+125 land on the same positions with the same shift: depth
    /// 1024 came back as 525 rows.
    ///
    /// So the row index is written into the sequence as a base-20 number over the
    /// first `digits` positions, which is injective by construction. A row that
    /// happens to reproduce the query is skipped rather than reasoned about, and the
    /// caller asserts the depth it actually got — belt and braces, because a silent
    /// shortfall here corrupts the measurement rather than failing it.
    static func a3m(query: String, depth: Int) -> String {
        let residues = Array(query)
        let alphabet = Array("ACDEFGHIKLMNPQRSTVWY")
        let radix = alphabet.count
        // Enough digits to encode every row index: 20^4 = 160,000 > any depth here.
        var digits = 1
        while pow(Double(radix), Double(digits)) < Double(depth) { digits += 1 }
        precondition(residues.count >= digits, "query is too short to index the rows")

        var lines = [">query", query]
        var seen: Set<String> = [query]
        var row = 1
        while seen.count < depth {
            var mutated = residues
            var value = row
            for position in 0 ..< digits {
                mutated[position] = alphabet[value % radix]
                value /= radix
            }
            let sequence = String(mutated)
            row += 1
            // The one row whose encoding reproduces the query would collide.
            guard seen.insert(sequence).inserted else { continue }
            lines.append(">homolog_\(seen.count - 1)")
            lines.append(sequence)
        }
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - The sweep

    func testMeasurePeakMemoryOverTokensAndDepth() throws {
        try XCTSkipUnless(
            ProcessInfo.processInfo.environment["RAYMOL_PREDICT_MSA_SWEEP"] == "1",
            "Memory sweep; set RAYMOL_PREDICT_MSA_SWEEP=1 to enable (runs real "
            + "predictions, tens of minutes).")
        let directory = Self.weightsDirectory
        try XCTSkipUnless(
            FileManager.default.fileExists(atPath: directory.path),
            "boltz2 weights are not cached at \(directory.path); run "
            + "`predict_weights boltz2, download=1` first.")

        // Exactly what BoltzJobManager does, so the numbers describe the app's runtime
        // and not this test's. Both lines matter: the cache limit changes what MLX holds
        // between allocations, and `.desktop` is the limit set the app runs under.
        BoltzRuntime.configureOnce()
        let predictor = try BoltzRuntime.withMLXErrorsAsThrows {
            try BoltzPredictor(
                modelDirectory: directory,
                memoryPlanner: MemoryPlanner(limits: .desktop,
                                             cacheLimit: MLXRuntime.activeCacheLimitBytes))
        }

        var options = BoltzPredictionOptions()
        options.recyclingSteps = 3
        options.diffusionSteps = 200
        options.seed = 0

        // Throw one prediction away first. Measured: the FIRST prediction in a process
        // reports a peak 12% below what the identical input reports once the process is
        // warm (115 tokens / depth 1 gave 2.12 GB in one run and 1.86 GB in another,
        // both as the first cell), while every warm cell reproduces across runs to the
        // second decimal — 2.27 and 2.37 GB, twice each. An optimistic first cell is the
        // one direction this table must never be wrong in, so it is not measured cold.
        _ = try BoltzRuntime.withMLXErrorsAsThrows {
            try Self.awaitSyncThrowing {
                try await predictor.predictScored(
                    featurized: try BoltzFeaturizer().featurize(
                        try CanonicalStructure.fromSequences(
                            [("A", Self.sequence(length: 60))])),
                    options: options)
            }
        }
        BoltzRuntime.configureOnce()

        print("SWEEP,tokens,depth,peak_bytes,peak_gb,seconds")
        // Cheapest first, so a run that has to be cut short still leaves a usable table
        // and the point it died on is the expensive corner rather than a random cell.
        for tokens in Self.tokenCounts {
            let query = Self.sequence(length: tokens)
            for depth in Self.depths {
                let alignment = try MSAAlignment.a3m(Self.a3m(query: query, depth: depth),
                                                     maximumSequences: depth,
                                                     taxonomy: nil)
                // Fatal, not a soft assertion: a fixture that deduplicated measures a
                // shallower alignment than the label says, and every line after it
                // would be quietly mislabelled rather than missing.
                guard alignment.depth == depth, alignment.queryLength == tokens else {
                    return XCTFail("fixture is wrong at \(tokens) tokens / depth "
                                   + "\(depth): got \(alignment.depth) rows x "
                                   + "\(alignment.queryLength) columns")
                }

                let canonical = try CanonicalStructure.fromSequences([("A", query)])
                let features = try BoltzFeaturizer().featurize(canonical,
                                                               alignments: ["A": alignment])

                Self.awaitSync { await predictor.resetPeakMemory() }
                let started = Date()
                _ = try BoltzRuntime.withMLXErrorsAsThrows {
                    try Self.awaitSyncThrowing {
                        try await predictor.predictScored(featurized: features,
                                                          options: options)
                    }
                }
                let seconds = Date().timeIntervalSince(started)
                let peak = Self.awaitSyncValue { await predictor.memorySnapshot().peakMemory }
                // One line per point, machine-readable, flushed as it goes: a sweep that
                // is killed part way through must still have published what it measured.
                // %ld, not %d: peak is an Int and every interesting value here is
                // above 2^31, which %d truncates to a negative number.
                print(String(format: "SWEEP,%ld,%ld,%ld,%.2f,%.1f",
                             tokens, depth, peak, Double(peak) / 1e9, seconds))
                fflush(stdout)
                BoltzRuntime.configureOnce()
            }
        }
    }

    // MARK: - async bridging, as BoltzJobManager does it

    private static func awaitSync(_ body: @escaping () async -> Void) {
        let done = DispatchSemaphore(value: 0)
        Task { await body(); done.signal() }
        done.wait()
    }

    private static func awaitSyncValue<T>(_ body: @escaping () async -> T) -> T {
        let done = DispatchSemaphore(value: 0)
        var out: T!
        Task { out = await body(); done.signal() }
        done.wait()
        return out
    }

    private static func awaitSyncThrowing<T>(_ body: @escaping () async throws -> T) throws -> T {
        let done = DispatchSemaphore(value: 0)
        var outcome: Result<T, Error>!
        Task {
            do { outcome = .success(try await body()) } catch { outcome = .failure(error) }
            done.signal()
        }
        done.wait()
        return try outcome.get()
    }
}
#endif
