"""Everything in the set store that has to ASK THE SESSION (#415).

The one module in `pymol.sets` that imports `cmd`. Four jobs:

  capture   an object (or a file, via the peek object) becomes entries: chains as CIF
            blobs, sequences, and every metrics-store run on it as columns and arrays
  stage     an entry becomes an object in the set's group, superposed on the reference,
            with its metrics written back into the metrics store; unstage reverses it
  peek      one hidden object, `_raymol_peek`, shows an entry without staging it
  session   `save x.raymol` / `load x.raymol`, and what `.pse` save and load do to the
            store (warn, and clear, respectively)

Nothing here is reached by a poll. The Swift side (#417) will read the database itself
and call these through `set_*` commands.
"""
import contextlib
import json
import os
import pickle

from pymol import cmd, colorprinting
from pymol.metrics import binding as mbinding, schema as mschema, store as mstore
from pymol.metrics.errors import MetricError

from . import document, store
from .errors import (SetBudgetExceeded, SetFormatError, SetInputError, SetNameConflict,
                     SetNotFound)

#: The peek object. The leading underscore keeps it out of `get_names('public_objects')`,
#: so the object panel and the sequence rows never see it; `session_save` strips it from
#: a .pse as well, so it cannot come back from a file as a real object.
PEEK = '_raymol_peek'

#: Default stage budget when neither the set nor the container says otherwise. Small on
#: purpose; the structure-count measurements in the MCP notes are the place to read
#: before raising it.
DEFAULT_BUDGET = 6

_SAVING_RAYMOL = False    # suppresses the .pse warning while the container's own blob is built


def container():
    return store.active()


# -- Small session helpers ---------------------------------------------------------


def _exists(name, _self=cmd):
    return name in (_self.get_names('all') or [])


def _legal(name, _self=cmd):
    return _self.get_legal_name(str(name))


def _chains(sel, _self=cmd):
    return list(_self.get_chains(sel) or [])


def _chain_sel(obj, chain):
    return '(%s) and chain %s' % (obj, chain if chain else '""')


def _sequence(sel, state, _self=cmd):
    """One-letter sequence of the polymer in `sel`, or ''."""
    try:
        text = _self.get_fastastr('(%s) and polymer' % sel, state) or ''
    except Exception:
        return ''
    return ''.join(line.strip() for line in text.splitlines()
                   if line and not line.startswith('>'))


def _load_cif_text(text, name, _self=cmd):
    _self.load_raw(text, 'cif', name, state=0, finish=1, discrete=-1, quiet=1,
                   multiplex=None, zoom=0)


def _split_cif_blocks(text):
    """The `data_` blocks of a CIF file as (label, text) pairs, in order. Anything
    before the first `data_` line (PyMOL's `# generated by` comment) is dropped: it is
    not a block, and loading it would create nothing."""
    blocks, current, label = [], [], None
    for line in text.splitlines(keepends=True):
        if line.startswith('data_'):
            if label is not None:
                blocks.append((label, ''.join(current)))
            current, label = [line], line[5:].strip()
        elif label is not None:
            current.append(line)
    if label is not None:
        blocks.append((label, ''.join(current)))
    return blocks


#: CIF items whose value is the exporting object's name (see `canonical_cif`).
_OBJECT_ID_TAGS = ('_entry.id ', '_cell.entry_id ', '_symmetry.entry_id ')


def canonical_cif(text, label):
    """`get_cifstr` output with its object-derived header lines replaced by `label`.

    Blobs are content-addressed by the sha256 of this text, and the one thing that
    differs between the same chain exported from two objects is the object's NAME:
    measured on two objects holding one chain A, the outputs differed in exactly two
    lines, `data_<object>` and `_entry.id <object>`, and every `_atom_site` row was
    byte-identical (`dss` writes nothing into the CIF -- there is no `_struct_conf`).
    Rewriting those two lines to the chain id is what makes a target held fixed across a
    1000-design batch ONE blob rather than 1000 (#416), and makes `set_add` of two
    objects sharing a chain dedupe as the store spec (§2.3) intended. Nothing that reads
    a blob looks at the label: `_load_chains` ignores it, `write_folder` concatenates
    blocks, `_split_cif_blocks` splits on `data_` whatever follows.
    """
    label = ''.join(ch if ch.isalnum() or ch in '_-' else '_' for ch in str(label)) or '_'
    out = []
    for line in text.splitlines(keepends=True):
        if line.startswith('data_'):
            line = 'data_%s\n' % label
        elif line.startswith(_OBJECT_ID_TAGS):
            # `_entry.id`, and on anything with a unit cell `_cell.entry_id` and
            # `_symmetry.entry_id` too (#545 review): all three carry the object name.
            line = '%s %s\n' % (line.split(None, 1)[0], label)
        out.append(line)
    return ''.join(out)


def _unique_entry_name(c, set_id, base):
    """`base`, or `base_2`, `base_3`... -- the first not yet in the set. Names from
    objects and files are made unique rather than refused (spec §4): a folder import
    into a set that already holds `d_0417` must not stop halfway.

    One point lookup PER CANDIDATE, not one full read of the set. The loop almost always
    runs once, and `has_entry_name` hits the `UNIQUE (set_id, name)` index; reading every
    row instead made a 1000-entry batch's delivery quadratic and cost 11 s of main thread
    (#453 review, measured).
    """
    candidate, n = base, 1
    while c.has_entry_name(set_id, candidate):
        n += 1
        candidate = '%s_%d' % (base, n)
    return candidate


def _load_chains(chains, obj, _self=cmd):
    """An entry's chain CIFs as ONE object.

    The CIF reader refuses to load into an existing object ("please use 'create' to
    append"), so each chain goes into its own hidden temporary and one `create` merges
    them. `_`-prefixed temporaries stay out of the panel for the instant they exist.
    """
    temps = []
    try:
        for i, (_chain, text) in enumerate(chains):
            temp = '_raymol_chain_%d' % i
            if _exists(temp, _self=_self):
                _self.delete(temp)
            _load_cif_text(text, temp, _self=_self)
            temps.append(temp)
        if _exists(obj, _self=_self):
            _self.delete(obj)
        _self.create(obj, ' or '.join(temps), zoom=0, quiet=1)
    finally:
        for temp in temps:
            if _exists(temp, _self=_self):
                _self.delete(temp)


def _reserved_column(key, chain=None):
    """True when the wide-table column for (key, chain) would clash with an `entries`
    field. Never raises: an undeclarable key is skipped, not fatal, at capture."""
    try:
        from . import schema
        return schema.column_name(key, chain) in schema.RESERVED_COLUMNS
    except Exception:
        return False


def _spec_or_none(tool, key):
    """`MetricSpec` for a declared (tool, key), else None. `schema.spec` raises for an
    undeclared tool or key; here absence is a normal case, not an error."""
    try:
        return mschema.spec(tool, key)
    except MetricError:
        return None


def _superpose(obj, ref, _self=cmd, ref_sel=None):
    """`super` obj onto ref; a failure is a warning, never an error. `ref_sel` is the
    selection to superpose onto when it is more than the reference object itself -- a
    reference staged as its design chain over a shared target (#545)."""
    if not ref or ref == obj or not _exists(ref, _self=_self):
        return False
    target = ref_sel or ref
    try:
        if _self.count_atoms('(%s) and polymer' % obj) == 0 or \
                _self.count_atoms('(%s) and polymer' % target) == 0:
            return False
        _self.super(obj, target, quiet=1)
        return True
    except Exception as exc:
        colorprinting.warning(' sets: could not superpose %s onto %s (%s)' % (obj, ref, exc))
        return False


def _group_children(group, _self=cmd):
    """Names whose parent is `group`, or None if unknown. From the session record, for
    the reason designing._group_children gives: `get_object_list` misses zero-atom
    members and answers "empty" for a group that is not."""
    try:
        return [entry[0] for entry in (_self.get_session(partial=1).get('names') or [])
                if entry and len(entry) > 6 and entry[6] == group]
    except Exception:
        return None


# -- Capture: object -> entries ------------------------------------------------------


def _metric_payload(obj, state):
    """(scalars, arrays, specs, runs) from every metrics-store run on `obj` for `state`.

    Object-scope values apply to every state. State-bearing values are taken only when
    they name this state, or name none.
    """
    scalars, arrays, specs, runs = {}, [], [], []
    for run in mstore.runs(object=obj):
        runs.append(run)
        for entry in run.values:
            if entry.state is not None and int(entry.state) != int(state):
                continue
            if not entry.is_array and _reserved_column(entry.key, entry.chain):
                # `n_residues` and `n_chains` are metrics every generator and predictor
                # declares (SHARED_INPUT_SPECS) AND fields of the `entries` row, which
                # the store computes from the chains it is given. The row's answer is
                # the one the table shows; refusing the whole entry over a duplicate of
                # it (which `declare_columns` would, correctly, do) lost every design
                # of a batch to a fact the entry already carried. Found by #416, latent
                # since #415 for `set_add` of any predicted object.
                continue
            spec = _spec_or_none(run.tool, entry.key)
            spec_dict = dict(spec.as_dict()) if spec is not None else \
                {'key': entry.key, 'scope': entry.scope, 'dtype': 'float'}
            spec_dict['tool'] = run.tool
            if entry.is_array:
                if entry.chain:
                    spec_dict = dict(spec_dict, chain=entry.chain)
                arrays.append({'key': entry.key, 'scope': entry.scope,
                               'chain': entry.chain, 'index': list(entry.index),
                               'values': list(entry.values), 'spec': spec_dict})
                specs.append(spec_dict)
            else:
                if entry.chain:
                    spec_dict = dict(spec_dict, chain=entry.chain)
                    scalars[(entry.key, entry.chain)] = entry.value
                else:
                    scalars[entry.key] = entry.value
                specs.append(spec_dict)
    return scalars, arrays, specs, runs


def capture_object(set_id, obj, name='', run_id=None, parents=(), states='all',
                   scalars=None, specs=(), _self=cmd):
    # `run_id`: a set run to attach the entries to (provenance). None means "derive one
    # per metrics-store run on the object", which is what a captured prediction wants.
    """Add `obj` to a set. One entry per state (`states='all'`), the current state only
    (`states='current'`), or ONE named state (`states=<int>`). Returns the new entry ids.

    Chains are stored as one CIF blob each, from `get_cifstr` with a canonical header
    (`canonical_cif`), so a chain shared by many entries is one blob. Sequences come from
    the polymer of each chain. Metrics are the metrics store's runs on the object,
    narrowed to the state. `scalars` / `specs` are extra columns written on the same
    call -- what a delivering tool knows and the metrics store does not, such as the seed
    a design ran at or which model of an `n_models` run this is (#416).

    An int `states` exists for delivery: a live design with `keep_frames=1` has the
    finished design in its LAST state, and the global `get_state()` may point anywhere.
    """
    if not _exists(obj, _self=_self):
        raise SetNotFound('no object %r' % obj)
    c = container()
    n_states = max(1, int(_self.count_states(obj) or 1))
    if isinstance(states, int) and not isinstance(states, bool):
        state_list = [min(max(int(states), 1), n_states)]
    elif states == 'current':
        cur = int(_self.get_state() or 1)
        state_list = [min(max(cur, 1), n_states)]
    else:
        state_list = list(range(1, n_states + 1))
    base = store.legal_entry_name(name or obj)
    chains = _chains(obj, _self=_self)
    ids = []
    for state in state_list:
        entry_name = base if len(state_list) == 1 else '%s_%d' % (base, state)
        entry_name = _unique_entry_name(c, set_id, entry_name)
        cifs, seqs = [], {}
        # A staged binder shown over its set's shared target is captured WITH the
        # target (#545 review): the entry is the complex, not the half on display.
        with complex_of(obj, state, _self=_self) as (src, src_state):
            for ch in (chains if src == obj else _chains(src, _self=_self)):
                sel = _chain_sel(src, ch)
                try:
                    text = _self.get_cifstr(sel, src_state)
                except Exception as exc:
                    raise SetInputError('could not export %s chain %r: %s' % (obj, ch, exc))
                if not text or not text.strip():
                    continue
                cifs.append((ch, canonical_cif(text, ch)))
                seq = _sequence(sel, src_state, _self=_self)
                if seq:
                    seqs[ch] = seq
        m_scalars, arrays, m_specs, runs = _metric_payload(obj, state)
        this_run = run_id
        if this_run is None and runs:
            # One set-level run per metrics run id, so provenance is not duplicated
            # per entry: the tool and its inputs are written once and shared.
            first = runs[0]
            this_run = _run_for(c, set_id, first)
        # The caller's columns are declared and written beside the metrics ones, on
        # the same add_entry, so an entry lands whole or not at all.
        all_specs = list(m_specs) + list(specs or ())
        all_scalars = dict(m_scalars)
        all_scalars.update(dict(scalars or {}))
        ids.append(c.add_entry(set_id, entry_name, run_id=this_run, sequences=seqs,
                               parents=parents, chains=cifs, scalars=all_scalars,
                               arrays=arrays, specs=all_specs))
    return ids


_RUN_MAP = {}   # (store generation, set id, metrics run id) -> set run id


def _run_for(c, set_id, run):
    key = (store.generation(), set_id, run.id)
    if key not in _RUN_MAP:
        _RUN_MAP[key] = c.add_run(set_id, run.tool, tool_version=run.tool_version,
                                  inputs=run.inputs, note='from metrics run %s' % run.id)
    return _RUN_MAP[key]


def capture_file(set_id, path, name='', run_id=None, parents=(), _self=cmd):
    """Add a structure file to a set by loading it into the peek object and capturing
    that. The one path for files, so a file and an object always yield the same entry."""
    if not os.path.isfile(path):
        raise SetInputError('no such file: %s' % path)
    clear_peek(_self=_self)
    try:
        blocks = []
        if path.lower().endswith(('.cif', '.mmcif')):
            with open(path, errors='replace') as handle:
                blocks = _split_cif_blocks(handle.read())
        if len(blocks) > 1:
            # A set export: one data block per chain. PyMOL would make one object per
            # block, so merge them the way staging does.
            _load_chains([(label, text) for label, text in blocks], PEEK, _self=_self)
        else:
            _self.load(path, PEEK, zoom=0, quiet=1)
    except SetInputError:
        raise
    except Exception as exc:
        raise SetInputError('could not read %s: %s' % (path, exc))
    if not _exists(PEEK, _self=_self):
        # `load` multiplexed into objects named after the file's own blocks.
        raise SetInputError('%s did not load as one object; is it a multi-block CIF'
                            ' with a single chain per block?' % path)
    try:
        return capture_object(set_id, PEEK, name=name or document.stem(path),
                              run_id=run_id, parents=parents, _self=_self)
    finally:
        clear_peek(_self=_self)


def capture_folder(set_id, folder, _self=cmd):
    """Every structure file in a folder, plus the sidecar's columns if it has one."""
    c = container()
    files, sidecar = document.scan_folder(folder)
    rows = document.read_sidecar(sidecar) if sidecar else {}
    known = {col['column'] for col in c.columns(set_id) if col.get('column')}
    extra = document.sidecar_columns(rows, known)
    if extra:
        c.declare_columns(set_id, [{'key': col, 'scope': 'object', 'dtype': dtype,
                                    'tool': 'import'} for col, dtype in extra])
    ids = []
    coltypes = {col['column']: col.get('dtype', 'float') for col in c.columns(set_id)
                if col.get('column')}
    for path in files:
        entry_name = document.stem(path)
        new_ids = capture_file(set_id, path, name=entry_name, _self=_self)
        ids.extend(new_ids)
        row = rows.get(entry_name)
        if row and new_ids:
            _apply_sidecar_row(c, new_ids[0], row, coltypes)
    # Sequence-only rows: in the sidecar but with no structure file.
    for entry_name, row in rows.items():
        if any(document.stem(p) == entry_name for p in files):
            continue
        try:
            seqs = json.loads(row.get('sequences') or '{}')
        except ValueError:
            seqs = {}
        eid = c.add_entry(set_id, entry_name, sequences=seqs)
        _apply_sidecar_row(c, eid, row, coltypes)
        ids.append(eid)
    return ids


def _apply_sidecar_row(c, entry_id, row, coltypes):
    fields = {}
    if row.get('starred', '') != '':
        fields['starred'] = int(document.coerce_sidecar_value('bool', row['starred']))
    if row.get('rejected', '') != '':
        fields['rejected'] = int(document.coerce_sidecar_value('bool', row['rejected']))
    for key in ('tags', 'note'):
        if row.get(key):
            fields[key] = row[key]
    if row.get('parents'):
        try:
            parents = json.loads(row['parents'])
        except ValueError:
            parents = [p for p in row['parents'].split('+') if p]
        if isinstance(parents, list):
            fields['parents'] = parents
    if fields:
        c.update_entry(entry_id, **fields)
    for col, dtype in coltypes.items():
        if col in row and row[col] != '':
            c.set_scalar(entry_id, col, document.coerce_sidecar_value(dtype, row[col]))


def capture_fasta(set_id, path, _self=cmd):
    c = container()
    return [c.add_entry(set_id, name, sequences={'A': seq})
            for name, seq in document.read_fasta(path)]


# -- Stage / unstage ------------------------------------------------------------------


def budget(set_row):
    if set_row.get('budget'):
        return int(set_row['budget'])
    raw = container().meta_get('stage_budget', None)
    try:
        return int(raw) if raw not in (None, '') else DEFAULT_BUDGET
    except ValueError:
        return DEFAULT_BUDGET


def _staged(c, set_id, _self=cmd):
    """Entries whose staged object still exists. A link to an object the user deleted
    is cleared here, so a ghost never counts against the budget or blocks a re-stage."""
    present = set(_self.get_names('all') or [])
    live = []
    for e in c.entries(set_id, where='e.staged_object IS NOT NULL'):
        if e['staged_object'] in present:
            live.append(e)
        else:
            c.update_entry(e['id'], staged_object=None, pinned=0)
    return live


def _free_object_name(name, _self=cmd):
    base = _legal(name, _self=_self)
    candidate, n = base, 1
    while _exists(candidate, _self=_self):
        n += 1
        candidate = '%s_%d' % (base, n)
    return candidate


def _ensure_group(group, _self=cmd):
    if group in (_self.get_names('public_group_objects') or []):
        return
    if _exists(group, _self=_self):
        raise SetNameConflict('%r is an object, not a group; rename the set or the object'
                              % group)
    _self.group(group, quiet=1)


# -- The shared target (#545) -----------------------------------------------------------
#
# A binder-design run holds its target fixed, so every entry carries the same target
# chain -- ONE blob (see `canonical_cif`) -- and staging six of them used to put six
# copies of it in the scene. Instead, an entry whose non-design chains are that one
# blob stages as its design chain(s) only, over a single `target_<set>` object in the
# set's group (see `target_name`), loaded once. Identity is decided by content hash, never assumed:
#
#   * the entry names its design chains, has at least one other chain, and
#   * its run HELD THE REST FIXED -- a design run, whose inputs name the `design_chain`
#     it generated against a given target. A fold predicts every chain, and its first
#     model to land cannot know the second will differ, so hash identity alone would
#     split one model of a Boltz run and stage the rest whole -- and
#   * every entry of its RUN holds the same blob for each of those other chains, and
#   * that is the blob the set's shared target already holds (or there is none yet), and
#   * no metric of the entry is tied to a non-design chain (a chain scalar, or a residue
#     array indexed on the target), because those could not be written back onto a
#     binder-only object -- such an entry is staged whole, so no metric is ever dropped.
#
# Anything else is staged whole, exactly as before (a fold predicts every chain, so its
# target differs per entry). The target is an Object, not an Entry: it is never counted
# against the budget, it goes into a .pse as a plain object, and it is removed when the
# last entry staged over it leaves the scene. Its record lives in the container
# (`Container.shared_target`), so a saved or recovered session keeps the link.


def target_name(group):
    """`target_<set>`, the shared target's object name.

    NOT `<set>_target`, which is what #545 first asked for: PyMOL resolves a selection
    word that names no object by UNIQUE PREFIX (`SelectGetInfoIter`) before it expands
    groups, so a lone `rfd3_a1_target` inside the group `rfd3_a1` made `hide rfd3_a1`,
    `color red, rfd3_a1` and `get_object_list('rfd3_a1')` act on the target alone and
    never reach the binders (measured). A name the group's name is not a prefix of
    cannot shadow it -- which `target_<set>` is not, for a set called `t`, `ta`,
    `target` or `target_t`, so those take the next prefix that is safe."""
    for prefix in ('target_', 'shared_', 'fixed_'):
        name = prefix + str(group)
        if not name.startswith(str(group)):
            return name
    return 'target_of_' + str(group)


def _target_record(c, set_id):
    record = c.shared_target(set_id)
    if record is None:
        return None
    record = dict(record)
    record['entries'] = [str(e) for e in record.get('entries') or ()]
    record['signature'] = [list(p) for p in record.get('signature') or ()]
    return record


def _chains_of_index(index):
    """Chain ids an array's `index` names: [[chain, resi], ...], or nested pairs."""
    out = set()
    for item in index or ():
        if isinstance(item, (list, tuple)) and len(item) == 2 and \
                not isinstance(item[0], (list, tuple)):
            out.add(str(item[0]))
        elif isinstance(item, (list, tuple)):
            out |= _chains_of_index(item)
    return out


def _metrics_touch_other_chains(c, entry, designed):
    """True when a metric of `entry` is tied to a chain outside `designed`."""
    designed = {str(ch) for ch in designed}
    scalars = entry.get('scalars') or {}
    for col in c.columns(entry['set_id']):
        chain = col.get('chain')
        if col.get('column') and chain not in (None, '') and str(chain) not in designed \
                and scalars.get(col['column']) is not None:
            return True
    for row in c.arrays_of(entry['id']):
        chain = row.get('chain')
        if chain not in (None, '') and str(chain) not in designed:
            return True
        if _chains_of_index(row.get('index')) - designed:
            return True
    return False


def split_plan(c, entry):
    """(design chains, target signature) when `entry` may stage as its design chains
    over the set's shared target, else None. See the block comment above."""
    designed = [str(ch) for ch in entry.get('design_chains') or ()]
    if not designed:
        return None
    held = c.chain_blobs(entry['id'])
    chains = [ch for ch, _ in held]
    if not set(designed) <= set(chains):
        return None
    signature = sorted([ch, h] for ch, h in held if ch not in designed)
    if not signature:
        return None
    if not entry.get('run_id'):
        return None
    try:
        inputs = c.run(entry['run_id']).get('inputs') or {}
    except Exception:
        return None
    if not isinstance(inputs, dict) or not inputs.get('design_chain'):
        return None
    per_chain = c.run_chain_blobs(entry['run_id'], [ch for ch, _ in signature])
    if any(len(hashes) != 1 for hashes in per_chain.values()):
        return None
    record = _target_record(c, entry['set_id'])
    if record is not None and record['entries'] and record['signature'] != signature:
        return None
    if _metrics_touch_other_chains(c, entry, designed):
        return None
    return designed, signature


def _chains_sel(obj, chains):
    return '(%s) and (%s)' % (obj, ' or '.join('chain %s' % (ch if ch else '""')
                                               for ch in chains))


def _show_target(target, _self=cmd):
    """The shared target's look, the same whichever path made it (#545 review): a
    cartoon, with ligands as sticks. A delivered design has its own target copy hidden
    (`designing._hide_target_copy`), so a target made from one would otherwise inherit
    "hidden" -- and one made by `stage` would not."""
    try:
        _self.hide('everything', target)
        _self.show('cartoon', target)
        _self.show('sticks', '(%s) and organic' % target)
    except Exception:
        pass


def _fit_onto_target(obj, target, designed, _self=cmd):
    """Move the whole complex in `obj` so its non-design chains lie on the shared
    target. Their atoms are the target's, blob for blob, so the fit is exact: the binder
    lands where its own complex puts it relative to THIS target, wherever the target
    or the reference has been moved since (#545 review)."""
    mobile = '(%s) and not (%s)' % (obj, _chains_sel(obj, designed))
    try:
        _self.fit(mobile, target, mobile_state=0, target_state=1, quiet=1)
        return True
    except Exception as exc:
        colorprinting.warning(' sets: could not fit %s onto %s (%s)' % (obj, target, exc))
        return False


def place(c, set_row, entry, obj, superpose=True, allow_split=True, _self=cmd):
    """Place a whole complex that was just loaded (or delivered) as `entry`'s staged
    object, link it, and -- when `split_plan` allows -- reduce it to its design chains
    over the set's shared target. Returns the plan, or None when staged whole.

    Placement: over an existing shared target, the complex is FIT onto it by its target
    chains; otherwise it is superposed onto the reference when `superpose` (what
    staging always did), and a target made now is made from it. One rule for `stage` and
    for batch delivery, so a set never mixes placements.

    If anything after the target was created fails, the target is removed again rather
    than left orphaned with no record naming it."""
    plan = split_plan(c, entry) if allow_split else None
    record = _target_record(c, set_row['id'])
    existing = record['object'] if record else ''
    if plan and existing and _exists(existing, _self=_self):
        _fit_onto_target(obj, existing, plan[0], _self=_self)
    elif superpose and set_row.get('reference'):
        _superpose(obj, set_row['reference'], _self=_self,
                   ref_sel=_reference_selection(c, set_row, _self=_self))
    created = ''
    try:
        target = ''
        if plan:
            target, created = _share_target(c, set_row, obj, plan, _self=_self)
        c.update_entry(entry['id'], staged_object=obj)
        if plan:
            _adopt_target(c, set_row, entry['id'], target, plan[1])
    except Exception:
        if created and _exists(created, _self=_self) and \
                not (_target_record(c, set_row['id']) or {}).get('entries'):
            try:
                _self.delete(created)
            except Exception:
                pass
        raise
    return plan


def _share_target(c, set_row, obj, plan, _self=cmd):
    """Reduce the whole complex in `obj` to its design chains, putting the rest in the
    set's shared target (made from `obj`'s own atoms, so it sits exactly where this
    complex was placed, when there is none yet). Returns the target's object name.

    The entry's link and the target's user list are written by the caller AFTER this
    returns, and the target object exists before its record names it: a `delete` in
    here runs `reconcile`, which must never see a record with no live user."""
    designed, signature = plan
    group = set_row.get('group_name') or set_row['name']
    record = _target_record(c, set_row['id'])
    target = record['object'] if record else ''
    created = ''
    if not target or not _exists(target, _self=_self):
        # A record whose object the user deleted gets it back under the same name.
        target = target or _free_object_name(target_name(group), _self=_self)
        state = max(1, int(_self.count_states(obj) or 1))
        _self.create(target, '(%s) and not (%s)' % (obj, _chains_sel(obj, designed)),
                     source_state=state, target_state=1, zoom=0, quiet=1)
        created = target
        _show_target(target, _self=_self)
        if group in (_self.get_names('public_group_objects') or []):
            try:
                _self.group(group, target, 'add', quiet=1)
            except Exception as exc:
                colorprinting.warning(' sets: could not add %s to group %s (%s)'
                                      % (target, group, exc))
    _self.remove('(%s) and not (%s)' % (obj, _chains_sel(obj, designed)))
    return target, created


def _adopt_target(c, set_row, entry_id, target, signature):
    record = _target_record(c, set_row['id']) or {'entries': []}
    users = [e for e in record['entries'] if e != entry_id] + [entry_id]
    c.set_shared_target(set_row['id'], {'object': target, 'signature': signature,
                                        'entries': users})


def _settle_target(c, set_id, _self=cmd):
    """Drop users of the set's shared target that are no longer staged; when none is
    left, delete the target object and its record. Links are read as `_staged` leaves
    them, so call it after that."""
    record = _target_record(c, set_id)
    if record is None:
        return
    staged = {e['id'] for e in c.entries(set_id, where='e.staged_object IS NOT NULL')}
    users = [e for e in record['entries'] if e in staged]
    if users == record['entries']:
        return
    if users:
        c.set_shared_target(set_id, dict(record, entries=users))
        return
    c.set_shared_target(set_id, None)
    target = record['object']
    if _exists(target, _self=_self):
        try:
            mstore.forget_object(target)
        except Exception:
            pass
        _self.delete(target)


def shared_target_object(c, set_id, _self=cmd):
    """The set's shared target object's name when it is in the scene, else ''."""
    record = _target_record(c, set_id)
    if record and record['entries'] and _exists(record['object'], _self=_self):
        return record['object']
    return ''


def split_context(obj, _self=cmd):
    """The shared target object when `obj` is a staged entry shown as its design chains
    over it, else ''. What an object-level tool (`set_add`, `predict`,
    `design_sequences`) asks before reading `obj` as if it were the whole complex."""
    try:
        if not obj or not store.is_open():
            return ''
        c = container()
        targets = c.shared_targets()
        if not targets:
            return ''
        for set_id, record in targets.items():
            if not _exists(record.get('object'), _self=_self):
                continue
            users = set(str(e) for e in record.get('entries') or ())
            for e in c.entries(set_id, where='e.staged_object = ?', params=(str(obj),)):
                if e['id'] in users:
                    return record['object']
    except Exception:
        return ''
    return ''


@contextlib.contextmanager
def complex_of(obj, state=1, _self=cmd):
    """`(name, state)` to read `obj` from AS THE WHOLE COMPLEX. For a staged binder shown
    over a shared target that is a hidden scratch object holding `obj`'s `state` and
    the target, as they sit in the scene, deleted on exit; for anything else it is
    `(obj, state)` itself, untouched."""
    target = split_context(obj, _self=_self)
    if not target:
        yield obj, state
        return
    scratch = _self.get_unused_name('_raymol_complex')
    parts = [_self.get_unused_name('_raymol_part'), None]
    try:
        _self.create(parts[0], obj, source_state=int(state), target_state=1, zoom=0,
                     quiet=1)
        parts[1] = _self.get_unused_name('_raymol_part')
        _self.create(parts[1], target, source_state=1, target_state=1, zoom=0, quiet=1)
        _self.create(scratch, '%s or %s' % tuple(parts), zoom=0, quiet=1)
        _self.disable(scratch)
        yield scratch, 1
    finally:
        for name in parts + [scratch]:
            if name and _exists(name, _self=_self):
                _self.delete(name)


def _reference_selection(c, set_row, _self=cmd):
    """What to superpose onto: the reference, plus the shared target when the reference
    is an entry staged as its design chains over it (it holds only a binder)."""
    ref = set_row.get('reference') or ''
    record = _target_record(c, set_row['id'])
    if not ref or record is None or not _exists(record['object'], _self=_self):
        return None
    users = set(record['entries'])
    if any(e['staged_object'] == ref and e['id'] in users
           for e in c.entries(set_row['id'], where='e.staged_object IS NOT NULL')):
        return '(%s) or (%s)' % (ref, record['object'])
    return None


def _write_back_metrics(c, entry, obj, _self=cmd):
    """The entry's columns and arrays as metrics-store runs on the staged object, one run
    per tool this build declares. Undeclared tools and keys are skipped: the numbers stay
    in the set, they just cannot colour an object here."""
    columns = c.columns(entry['set_id'])
    array_tool = {col.get('key'): col.get('tool') or '' for col in columns
                  if not col.get('column')}
    by_tool = {}
    for col in columns:
        if not col.get('column'):
            continue                      # an array declaration; handled below
        tool = col.get('tool') or ''
        key = col.get('key') or col['column']
        if not tool or _spec_or_none(tool, key) is None:
            continue
        value = (entry.get('scalars') or {}).get(col['column'])
        if value is None:
            continue
        kw = {}
        if col.get('scope', 'object') == 'state':
            kw['state'] = 1
        if col.get('chain'):
            kw['chain'] = col['chain']
        by_tool.setdefault(tool, []).append(mstore.value(tool, key, value=value, **kw))
    for row in c.arrays_of(entry['id']):
        tool = array_tool.get(row['key'], '')
        if not tool or _spec_or_none(tool, row['key']) is None:
            continue
        index, values = c.array(entry['id'], row['key'], chain=row.get('chain'))
        kw = {'state': 1, 'index': [tuple(p) for p in index], 'values': values}
        if row.get('chain'):
            kw['chain'] = row['chain']
        by_tool.setdefault(tool, []).append(mstore.value(tool, row['key'], **kw))
    for tool, values in by_tool.items():
        try:
            mbinding.record(obj, tool, values, inputs={'set': entry['set_id'],
                                                       'entry': entry['name']},
                            _self=_self)
        except Exception as exc:
            colorprinting.warning(' sets: metrics for %s (%s) not written: %s'
                                  % (obj, tool, exc))


def _load_entry_into(c, entry, obj, _self=cmd):
    chains = c.chain_cifs(entry['id'])
    if not chains:
        raise SetInputError('%s has no structure to show' % entry['name'])
    _load_chains(chains, obj, _self=_self)
    try:
        _self.dss(obj)
    except Exception:
        pass


def stage(set_row, entries, budget_override=None, _self=cmd):
    """Load entries as objects in the set's group. Returns the object names.

    Refuses past the budget with the unpinned staged names it would need to drop; it
    never drops them itself. An entry already staged is left alone and its object name
    returned.
    """
    c = container()
    set_id = set_row['id']
    staged = _staged(c, set_id, _self=_self)
    _settle_target(c, set_id, _self=_self)      # a record naming only dead links
    already = {e['id'] for e in staged}
    todo = [e for e in entries if e['id'] not in already]
    limit = int(budget_override) if budget_override else budget(set_row)
    if len(staged) + len(todo) > limit:
        unpinned = [e['name'] for e in staged if not e.get('pinned')]
        raise SetBudgetExceeded(
            'staging %d more would put %d objects in the scene; the budget is %d.'
            ' Unstage some of: %s (or raise the budget with set_budget)'
            % (len(todo), len(staged) + len(todo), limit,
               ', '.join(unpinned) or 'nothing is unpinned'), unpinned=unpinned)
    names = [e['staged_object'] for e in entries if e['id'] in already]
    if not todo:
        return names
    group = set_row.get('group_name') or set_row['name']
    _ensure_group(group, _self=_self)
    for e in todo:
        obj = _free_object_name(e['name'], _self=_self)
        # Whole first, placed as a whole (fit onto the shared target, or superposed on
        # the reference), and only THEN reduced to its design chains, so a binder staged
        # over the shared target sits where its own complex puts it relative to it.
        _load_entry_into(c, e, obj, _self=_self)
        try:
            _self.group(group, obj, 'add', quiet=1)
        except Exception as exc:
            colorprinting.warning(' sets: could not add %s to group %s (%s)' % (obj, group, exc))
        place(c, set_row, e, obj, superpose=True, _self=_self)
        _write_back_metrics(c, dict(e, staged_object=obj), obj, _self=_self)
        names.append(obj)
    return names


def unstage(set_row, entries, include_pinned=False, _self=cmd):
    """Delete the entries' objects and their metrics runs; clear the links. Pinned
    entries are skipped unless `include_pinned` (the caller named them explicitly)."""
    c = container()
    removed = []
    for e in entries:
        obj = e.get('staged_object')
        if not obj:
            continue
        if e.get('pinned') and not include_pinned:
            continue
        if _exists(obj, _self=_self):
            try:
                mstore.forget_object(obj)
            except Exception:
                pass
            _self.delete(obj)
            removed.append(obj)
        c.update_entry(e['id'], staged_object=None, pinned=0)
    _settle_target(c, set_row['id'], _self=_self)
    _drop_empty_group(set_row, _self=_self)
    return removed


def _drop_empty_group(set_row, _self=cmd):
    group = set_row.get('group_name') or set_row['name']
    if group not in (_self.get_names('public_group_objects') or []):
        return
    if _staged(container(), set_row['id'], _self=_self):
        return
    children = _group_children(group, _self=_self)
    if children is None or children:
        return
    try:
        _self.delete(group)
    except Exception:
        pass


def on_objects_deleted(_self=cmd):
    """After `delete`: clear links whose object is gone, NOW, so a new object made
    under the same name is never mistaken for the entry that once bore it."""
    reconcile(_self=_self)


def on_object_renamed(old, new, _self=cmd):
    """After `set_name`: a staged object keeps its link under the new name."""
    if not store.is_open() or not old or old == new:
        return
    c = container()
    for s in c.sets():
        for e in c.entries(s['id'], where='e.staged_object = ?', params=(old,)):
            c.update_entry(e['id'], staged_object=new)
    for set_id, record in c.shared_targets().items():
        if record.get('object') == old:
            c.set_shared_target(set_id, dict(record, object=new))


def reconcile(_self=cmd):
    """Clear links whose object is gone (deleted by the user, or absent from the session
    that was just loaded). Called after every session restore."""
    if not store.is_open():
        return
    c = container()
    targets = c.shared_targets()
    for s in c.sets():
        _staged(c, s['id'], _self=_self)
        if s['id'] in targets:
            _settle_target(c, s['id'], _self=_self)
    for set_id in set(targets) - {s['id'] for s in c.sets()}:
        c.set_shared_target(set_id, None)        # its set is gone


# -- Peek ------------------------------------------------------------------------------


def clear_peek(_self=cmd):
    if _exists(PEEK, _self=_self):
        _self.delete(PEEK)


def peek(set_row, entry, _self=cmd):
    """Show one entry in the peek object, replacing whatever it showed. Fixed look: a
    dim, half-transparent cartoon, so it cannot be mistaken for a staged object."""
    c = container()
    clear_peek(_self=_self)
    _load_entry_into(c, entry, PEEK, _self=_self)
    _superpose(PEEK, set_row.get('reference') or '', _self=_self,
               ref_sel=_reference_selection(c, set_row, _self=_self))
    # Only the designed chain(s) (#545): the target is already on screen, and a ghost
    # of it drawn over itself is 141 residues of noise around a 60-residue binder.
    # Superposed WHOLE first, so the binder lands where its complex puts it.
    # Only for an entry that WOULD stage over the shared target: a fold whose target
    # really differs is ghosted whole, target and all (#545 review).
    plan = split_plan(c, entry)
    designed = list(plan[0]) if plan else []
    if designed and set(designed) < set(_chains(PEEK, _self=_self)):
        _self.remove('(%s) and not (%s)' % (PEEK, _chains_sel(PEEK, designed)))
    try:
        _self.hide('everything', PEEK)
        _self.show('cartoon', PEEK)
        _self.color('grey70', PEEK)
        _self.set('cartoon_transparency', 0.5, PEEK)
    except Exception:
        pass
    return PEEK


# -- Session: .raymol save/load, .pse save/load ------------------------------------------


def _strip_peek(session):
    names = session.get('names')
    if isinstance(names, list):
        session['names'] = [entry for entry in names
                            if not (entry and entry[0] == PEEK)]


def session_save(session, _self=cmd, **_kwargs):
    """Session-save task. Keeps the peek object out of every session dictionary, so it
    can never come back from a .pse as a real object. Never touches the store."""
    _strip_peek(session)
    return 1


def warn_if_pse_leaves_sets(filename='', _self=cmd):
    """Called by `save` on the .pse/.psw path (not from the session task: `get_session`
    is also used for reads like the group-membership check, and a warning on every read
    would be noise). Names the sets a plain .pse leaves behind.

    A set whose EVERY entry is staged is not named: each of its structures is an object
    in the .pse, so nothing is lost -- and since #416 every single design has a
    one-entry set behind it, a warning there would fire on every save of every session
    that ever ran a design. Only the links and the columns stay behind, which is what the
    words say.
    """
    if _SAVING_RAYMOL or not store.is_open():
        return False
    try:
        c = container()
        names = [s['name'] for s in c.sets()
                 if c.count(s['id']) > c.count(s['id'], 'e.staged_object IS NOT NULL')]
        # A set whose binders are staged over a shared target that is no longer in the
        # scene is ALSO left behind: the .pse holds only the binders (#545 review).
        by_id = {s['id']: s['name'] for s in c.sets()}
        for set_id, record in c.shared_targets().items():
            if record.get('entries') and not _exists(record.get('object'), _self=_self) \
                    and by_id.get(set_id) and by_id[set_id] not in names:
                names.append(by_id[set_id])
    except Exception:
        return False
    if not names:
        return False
    colorprinting.warning(
        ' sets: a .pse cannot hold sets; %s left out. Use `save name.raymol` to keep'
        ' the whole session in one file.' % ', '.join(names))
    return True


def session_restore(session, _self=cmd, **_kwargs):
    """Session-restore task: drop links to staged objects the incoming session does not
    have. Never resets the store -- `set_session` also restores in-memory snapshots
    (the theme preview) and partial loads merge, so the reset for a bare `load x.pse`
    lives in `importing.load_pse`, which knows it is one."""
    try:
        reconcile(_self=_self)
    except Exception as exc:
        colorprinting.warning(' sets: could not reconcile staged objects: %s' % exc)
    return 1


def _app_version(_self=cmd):
    try:
        return str(_self.get_version()[0])
    except Exception:
        return ''


def _pse_bytes(_self=cmd):
    global _SAVING_RAYMOL
    _SAVING_RAYMOL = True
    try:
        session = _self.get_session('', 0, 1)      # session_save strips the peek

        return pickle.dumps(session, 1)
    finally:
        _SAVING_RAYMOL = False


def save_raymol(filename, quiet=1, _self=cmd):
    """`save x.raymol`. If the open container is already this file, write the session
    blob; otherwise copy the container there and continue on the copy.

    Ordered so that no failure loses data: the copy is made to a temporary beside the
    target, the target and any stale `-wal`/`-shm` of a crashed session are removed
    only when the copy exists, the previous file is deleted only after the new one is
    open and holds the session, and on any failure the previous container is reopened
    and reinstalled.
    """
    filename = os.path.abspath(_self.exp_path(filename))
    c = container()
    same = os.path.exists(filename) and os.path.samefile(filename, c.path)
    if not same:
        old_path = c.path
        tmp = filename + '.saving'
        store.remove_db_files(tmp)
        try:
            moved = c.save_into(tmp)          # closes c
            moved.close()
            store.remove_db_files(filename)   # the target AND a stale WAL beside it
            os.replace(tmp, filename)
            c = store.replace(store.Container(filename))
        except Exception:
            store.remove_db_files(tmp)
            try:
                store.replace(store.Container(old_path))
            except Exception:
                pass
            raise
    try:
        c.write_session(_pse_bytes(_self=_self),
                        pse_version=_self.get_setting_float('pse_export_version'),
                        app_version=_app_version(_self=_self))
    except Exception as exc:
        raise SetInputError('could not write the session into %s: %s' % (filename, exc))
    if not same and (os.path.abspath(old_path) == os.path.abspath(store.working_path())
                     or store.is_preserved(old_path)):
        # force: the ONE place a non-empty working file may still be deleted (#447).
        # Everything in it was just copied into the document the user named, so
        # preserving it would offer them, on the next launch, a recovery of work they
        # explicitly saved -- and a second copy of every structure blob on disk.
        #
        # A PRESERVED container counts as a working file here (#447 review): Save As
        # from a recovered session is exactly the "now put it somewhere I chose" the
        # alert sends the user to, and leaving the recovered_ copy behind would offer
        # it back on the next launch, duplicate every structure blob, and make the
        # docs' "the next Save moves it where you want it" a lie.
        store.retire_working_file(old_path, force=True)
    _self.set('session_file', filename.replace('\\', '/'), quiet=1)
    if not int(quiet):
        colorprinting.parrot(' Save: wrote session and %d set(s) to %s'
                             % (len(c.sets()), filename))
    return _self.DEFAULT_SUCCESS


def checkpoint_session(_self=cmd):
    """Write the current session into the working container, so that what survives a
    quit carries the SCENE as well as the sets (#447, spec §2.1: "the working file for
    an untitled session IS the autosave").

    Called by the app on the way out, not on a timer: it pickles the whole session,
    which is the expensive half of a Save, and the cheap half (the entries) is already
    on disk the moment each result lands. A crash therefore still recovers the sets and
    loses the camera, which is the trade #415 already made everywhere else.

    A no-op unless there is something to protect: no container open (a session that
    never touched a set writes nothing anywhere), a real document open (⌘S is that
    session's answer, and writing behind the user's back is not), or a working file
    with no entries (it is deleted at exit, so a session blob in it is pure cost).
    Returns True when a blob was written.
    """
    if not store.is_open():
        return False
    c = store.active()
    if os.path.abspath(c.path) != os.path.abspath(store.working_path()):
        return False
    if not c.holds_entries():
        return False
    try:
        c.write_session(_pse_bytes(_self=_self),
                        pse_version=_self.get_setting_float('pse_export_version'),
                        app_version=_app_version(_self=_self))
    except Exception as exc:
        colorprinting.warning(' sets: could not checkpoint the session: %s' % exc)
        return False
    return True


def _read_session_readonly(path):
    """The session blob of `path` read through a READ-ONLY connection, or None when
    there is none or the file cannot be read that way (the container's own open then
    says why)."""
    import sqlite3
    from urllib.request import pathname2url
    try:
        conn = sqlite3.connect('file:%s?mode=ro' % pathname2url(path), uri=True)
    except Exception:
        return None
    try:
        row = conn.execute('SELECT pse FROM session WHERE id = 1').fetchone()
        return bytes(row[0]) if row and row[0] is not None else None
    except Exception:
        return None
    finally:
        conn.close()


def load_raymol(filename, partial=0, quiet=1, *, _self=cmd):
    """`load x.raymol`. Opens the container IN PLACE, then restores the session blob it
    carries. Later results write straight into the document.

    Validates everything it can before it changes anything: the file opens as ours and
    its session blob unpickles first, then the scene is cleared or replaced, and only
    then is the document installed and the previous working file removed. A partial
    load is refused: it would merge the scene but there is no meaning to merging two
    documents' sets.
    """
    if int(partial):
        raise SetInputError('a .raymol cannot be loaded partially; export the session'
                            ' as .pse and load that partially instead')
    filename = os.path.abspath(_self.exp_path(filename))
    if not os.path.isfile(filename):
        raise SetInputError('no such file: %s' % filename)
    # The session blob is read and unpickled BEFORE the container is opened, because
    # opening migrates an older file in place (#545 review): a file whose session this
    # build cannot read is refused untouched, not refused after it was upgraded.
    early = _read_session_readonly(filename)
    if early is not None:
        try:
            pickle.loads(early)
        except Exception as exc:
            raise SetFormatError('%s carries a session this build cannot read: %s'
                                 % (filename, exc))
    new = store.Container(filename)          # SetFormatError if it is not ours
    try:
        blob = new.read_session()
        session = pickle.loads(blob) if blob else None
    except Exception as exc:
        new.close()
        raise SetFormatError('%s carries a session this build cannot read: %s'
                             % (filename, exc))
    old = container()
    old_path = old.path
    if session is None:
        # A container written by the store alone (a batch that never saw Save, an
        # exported set) carries no session. Clear the scene FIRST: `reinitialize`
        # resets the store, which would close the document if it were installed.
        _self.reinitialize()
    store.replace(new)
    if session is not None:
        r = _self.set_session(session, quiet=quiet, partial=0, steal=1)
    else:
        r = _self.DEFAULT_SUCCESS
    reconcile(_self=_self)
    if os.path.abspath(old_path) == os.path.abspath(store.working_path()) \
            and os.path.abspath(old_path) != os.path.abspath(filename):
        # Not force: opening another document is not permission to discard what the
        # previous, untitled one holds. A batch that landed entries into the working
        # file keeps them, under a recovered_ name, and is offered back on the next
        # launch (#447; the floor of #448, which is about saying so at the time).
        kept = store.retire_working_file(old_path)
        if kept:
            colorprinting.warning(' sets: the previous session had sets that were never'
                                  ' saved; they were kept in %s' % kept)
    _self.set('session_file', filename.replace('\\', '/'), quiet=1)
    return r
