"""Everything in the set store that has to ASK THE SESSION (#415).

The one module in `pymol.sets` that imports `cmd`. Four jobs:

  capture   an object (or a file, via the peek object) becomes entries: chains as CIF
            blobs, sequences, and every metrics-store run on it as columns and arrays
  stage     an entry becomes an object in the set's group, superposed on the reference,
            with its metrics written back into the metrics store; unstage reverses it
  peek      one hidden object, `_raymol_peek`, shows an entry without staging it
  session   `save x.raymol` / `load x.raymol`, and what `.pse` save and load do to the
            store (warn, and clear, respectively)

Nothing here is reached by a poll. The Swift side (#417) will read the database itself
and call these through `set_*` commands.
"""
import contextlib
import json
import os
import pickle

from pymol import cmd, colorprinting
from pymol.metrics import binding as mbinding, schema as mschema, store as mstore
from pymol.metrics.errors import MetricError

from . import document, schema, store
from .errors import (SetBudgetExceeded, SetFormatError, SetInputError, SetNameConflict,
                     SetNotFound)

#: The peek object. The leading underscore keeps it out of `get_names('public_objects')`,
#: so the object panel and the sequence rows never see it; `session_save` strips it from
#: a .pse as well, so it cannot come back from a file as a real object.
PEEK = '_raymol_peek'

#: Default stage budget when neither the set nor the container says otherwise. Small on
#: purpose; the structure-count measurements in the MCP notes are the place to read
#: before raising it.
DEFAULT_BUDGET = 6

_SAVING_RAYMOL = False    # suppresses the .pse warning while the container's own blob is built


def container():
    return store.active()


# -- Small session helpers ---------------------------------------------------------


def _exists(name, _self=cmd):
    return name in (_self.get_names('all') or [])


def _legal(name, _self=cmd):
    return _self.get_legal_name(str(name))


def _chains(sel, _self=cmd):
    return list(_self.get_chains(sel) or [])


def _chain_sel(obj, chain):
    return '(%s) and chain %s' % (obj, chain if chain else '""')


def _sequence(sel, state, _self=cmd):
    """One-letter sequence of the polymer in `sel`, or ''."""
    try:
        text = _self.get_fastastr('(%s) and polymer' % sel, state) or ''
    except Exception:
        return ''
    return ''.join(line.strip() for line in text.splitlines()
                   if line and not line.startswith('>'))


def _load_cif_text(text, name, _self=cmd):
    _self.load_raw(text, 'cif', name, state=0, finish=1, discrete=-1, quiet=1,
                   multiplex=None, zoom=0)


def _split_cif_blocks(text):
    """The `data_` blocks of a CIF file as (label, text) pairs, in order. Anything
    before the first `data_` line (PyMOL's `# generated by` comment) is dropped: it is
    not a block, and loading it would create nothing."""
    blocks, current, label = [], [], None
    for line in text.splitlines(keepends=True):
        if line.startswith('data_'):
            if label is not None:
                blocks.append((label, ''.join(current)))
            current, label = [line], line[5:].strip()
        elif label is not None:
            current.append(line)
    if label is not None:
        blocks.append((label, ''.join(current)))
    return blocks


#: CIF items whose value is the exporting object's name (see `canonical_cif`).
_OBJECT_ID_TAGS = ('_entry.id ', '_cell.entry_id ', '_symmetry.entry_id ')


def canonical_cif(text, label):
    """`get_cifstr` output with its object-derived header lines replaced by `label`.

    Blobs are content-addressed by the sha256 of this text, and the one thing that
    differs between the same chain exported from two objects is the object's NAME:
    measured on two objects holding one chain A, the outputs differed in exactly two
    lines, `data_<object>` and `_entry.id <object>`, and every `_atom_site` row was
    byte-identical (`dss` writes nothing into the CIF -- there is no `_struct_conf`).
    Rewriting those two lines to the chain id is what makes a target held fixed across a
    1000-design batch ONE blob rather than 1000 (#416), and makes `set_add` of two
    objects sharing a chain dedupe as the store spec (§2.3) intended. Nothing that reads
    a blob looks at the label: `_load_chains` ignores it, `write_folder` concatenates
    blocks, `_split_cif_blocks` splits on `data_` whatever follows.
    """
    label = ''.join(ch if ch.isalnum() or ch in '_-' else '_' for ch in str(label)) or '_'
    out = []
    for line in text.splitlines(keepends=True):
        if line.startswith('data_'):
            line = 'data_%s\n' % label
        elif line.startswith(_OBJECT_ID_TAGS):
            # `_entry.id`, and on anything with a unit cell `_cell.entry_id` and
            # `_symmetry.entry_id` too (#545 review): all three carry the object name.
            line = '%s %s\n' % (line.split(None, 1)[0], label)
        out.append(line)
    return ''.join(out)


def _unique_entry_name(c, set_id, base):
    """`base`, or `base_2`, `base_3`... -- the first not yet in the set. Names from
    objects and files are made unique rather than refused (spec §4): a folder import
    into a set that already holds `d_0417` must not stop halfway.

    One point lookup PER CANDIDATE, not one full read of the set. The loop almost always
    runs once, and `has_entry_name` hits the `UNIQUE (set_id, name)` index; reading every
    row instead made a 1000-entry batch's delivery quadratic and cost 11 s of main thread
    (#453 review, measured).
    """
    candidate, n = base, 1
    while c.has_entry_name(set_id, candidate):
        n += 1
        candidate = '%s_%d' % (base, n)
    return candidate


def _load_chains(chains, obj, _self=cmd):
    """An entry's chain CIFs as ONE object.

    The CIF reader refuses to load into an existing object ("please use 'create' to
    append"), so each chain goes into its own hidden temporary and one `create` merges
    them. `_`-prefixed temporaries stay out of the panel for the instant they exist.
    """
    temps = []
    try:
        for i, (_chain, text) in enumerate(chains):
            temp = '_raymol_chain_%d' % i
            if _exists(temp, _self=_self):
                _self.delete(temp)
            _load_cif_text(text, temp, _self=_self)
            temps.append(temp)
        if _exists(obj, _self=_self):
            _self.delete(obj)
        _self.create(obj, ' or '.join(temps), zoom=0, quiet=1)
    finally:
        for temp in temps:
            if _exists(temp, _self=_self):
                _self.delete(temp)


def _reserved_column(key, chain=None):
    """True when the wide-table column for (key, chain) would clash with an `entries`
    field. Never raises: an undeclarable key is skipped, not fatal, at capture."""
    try:
        from . import schema
        return schema.column_name(key, chain) in schema.RESERVED_COLUMNS
    except Exception:
        return False


def _spec_or_none(tool, key):
    """`MetricSpec` for a declared (tool, key), else None. `schema.spec` raises for an
    undeclared tool or key; here absence is a normal case, not an error."""
    try:
        return mschema.spec(tool, key)
    except MetricError:
        return None


def _superpose(obj, ref, _self=cmd, ref_sel=None):
    """`super` obj onto ref; a failure is a warning, never an error. `ref_sel` is the
    selection to superpose onto when it is more than the reference object itself -- a
    reference staged as its design chain over a shared target (#545)."""
    if not ref or ref == obj or not _exists(ref, _self=_self):
        return False
    target = ref_sel or ref
    try:
        if _self.count_atoms('(%s) and polymer' % obj) == 0 or \
                _self.count_atoms('(%s) and polymer' % target) == 0:
            return False
        _self.super(obj, target, quiet=1)
        return True
    except Exception as exc:
        colorprinting.warning(' sets: could not superpose %s onto %s (%s)' % (obj, ref, exc))
        return False


def _group_children(group, _self=cmd):
    """Names whose parent is `group`, or None if unknown. From the session record, for
    the reason designing._group_children gives: `get_object_list` misses zero-atom
    members and answers "empty" for a group that is not."""
    try:
        return [entry[0] for entry in (_self.get_session(partial=1).get('names') or [])
                if entry and len(entry) > 6 and entry[6] == group]
    except Exception:
        return None


# -- Capture: object -> entries ------------------------------------------------------


def _metric_payload(obj, state):
    """(scalars, arrays, specs, runs) from every metrics-store run on `obj` for `state`.

    Object-scope values apply to every state. State-bearing values are taken only when
    they name this state, or name none.
    """
    scalars, arrays, specs, runs = {}, [], [], []
    for run in mstore.runs(object=obj):
        runs.append(run)
        for entry in run.values:
            if entry.state is not None and int(entry.state) != int(state):
                continue
            if not entry.is_array and _reserved_column(entry.key, entry.chain):
                # `n_residues` and `n_chains` are metrics every generator and predictor
                # declares (SHARED_INPUT_SPECS) AND fields of the `entries` row, which
                # the store computes from the chains it is given. The row's answer is
                # the one the table shows; refusing the whole entry over a duplicate of
                # it (which `declare_columns` would, correctly, do) lost every design
                # of a batch to a fact the entry already carried. Found by #416, latent
                # since #415 for `set_add` of any predicted object.
                continue
            spec = _spec_or_none(run.tool, entry.key)
            spec_dict = dict(spec.as_dict()) if spec is not None else \
                {'key': entry.key, 'scope': entry.scope, 'dtype': 'float'}
            spec_dict['tool'] = run.tool
            if entry.is_array:
                if entry.chain:
                    spec_dict = dict(spec_dict, chain=entry.chain)
                arrays.append({'key': entry.key, 'scope': entry.scope,
                               'chain': entry.chain, 'index': list(entry.index),
                               'values': list(entry.values), 'spec': spec_dict})
                specs.append(spec_dict)
            else:
                if entry.chain:
                    spec_dict = dict(spec_dict, chain=entry.chain)
                    scalars[(entry.key, entry.chain)] = entry.value
                else:
                    scalars[entry.key] = entry.value
                specs.append(spec_dict)
    return scalars, arrays, specs, runs


def capture_object(set_id, obj, name='', run_id=None, parents=(), states='all',
                   scalars=None, specs=(), into=None, _self=cmd):
    # `run_id`: a set run to attach the entries to (provenance). None means "derive one
    # per metrics-store run on the object", which is what a captured prediction wants.
    """Add `obj` to a set. One entry per state (`states='all'`), the current state only
    (`states='current'`), or ONE named state (`states=<int>`). Returns the new entry ids.

    Chains are stored as one CIF blob each, from `get_cifstr` with a canonical header
    (`canonical_cif`), so a chain shared by many entries is one blob. Sequences come from
    the polymer of each chain. Metrics are the metrics store's runs on the object,
    narrowed to the state. `scalars` / `specs` are extra columns written on the same
    call -- what a delivering tool knows and the metrics store does not, such as the seed
    a design ran at or which model of an `n_models` run this is (#416).

    An int `states` exists for delivery: a live design with `keep_frames=1` has the
    finished design in its LAST state, and the global `get_state()` may point anywhere.

    `into` is a container other than the active one, for exactly one caller: a batch
    whose session was replaced under it writes its later results back into ITS OWN
    document, which is no longer the open one (#448, `batch._land_away`). It needs an
    explicit `run_id`, since the per-metrics-run fallback is keyed on the active store.
    """
    if not _exists(obj, _self=_self):
        raise SetNotFound('no object %r' % obj)
    if into is not None and run_id is None:
        raise SetInputError('capturing into another container needs a run id')
    c = into if into is not None else container()
    n_states = max(1, int(_self.count_states(obj) or 1))
    if isinstance(states, int) and not isinstance(states, bool):
        state_list = [min(max(int(states), 1), n_states)]
    elif states == 'current':
        cur = int(_self.get_state() or 1)
        state_list = [min(max(cur, 1), n_states)]
    else:
        state_list = list(range(1, n_states + 1))
    base = store.legal_entry_name(name or obj)
    chains = _chains(obj, _self=_self)
    ids = []
    for state in state_list:
        entry_name = base if len(state_list) == 1 else '%s_%d' % (base, state)
        entry_name = _unique_entry_name(c, set_id, entry_name)
        cifs, seqs = [], {}
        # A staged binder shown over its set's shared target is captured WITH the
        # target (#545 review): the entry is the complex, not the half on display.
        # Not for `into=`: the staged-complex lookup reads the ACTIVE container, which
        # for an away delivery is an unrelated document (#448 review).
        reading = (contextlib.nullcontext((obj, state)) if into is not None
                   else complex_of(obj, state, _self=_self))
        with reading as (src, src_state):
            for ch in (chains if src == obj else _chains(src, _self=_self)):
                sel = _chain_sel(src, ch)
                try:
                    text = _self.get_cifstr(sel, src_state)
                except Exception as exc:
                    raise SetInputError('could not export %s chain %r: %s' % (obj, ch, exc))
                if not text or not text.strip():
                    continue
                cifs.append((ch, canonical_cif(text, ch)))
                seq = _sequence(sel, src_state, _self=_self)
                if seq:
                    seqs[ch] = seq
        m_scalars, arrays, m_specs, runs = _metric_payload(obj, state)
        this_run = run_id
        if this_run is None and runs:
            # One set-level run per metrics run id, so provenance is not duplicated
            # per entry: the tool and its inputs are written once and shared.
            first = runs[0]
            this_run = _run_for(c, set_id, first)
        # The caller's columns are declared and written beside the metrics ones, on
        # the same add_entry, so an entry lands whole or not at all.
        all_specs = list(m_specs) + list(specs or ())
        all_scalars = dict(m_scalars)
        all_scalars.update(dict(scalars or {}))
        ids.append(c.add_entry(set_id, entry_name, run_id=this_run, sequences=seqs,
                               parents=parents, chains=cifs, scalars=all_scalars,
                               arrays=arrays, specs=all_specs))
    return ids


_RUN_MAP = {}   # (store generation, set id, metrics run id) -> set run id


def _run_for(c, set_id, run):
    key = (store.generation(), set_id, run.id)
    if key not in _RUN_MAP:
        _RUN_MAP[key] = c.add_run(set_id, run.tool, tool_version=run.tool_version,
                                  inputs=run.inputs, note='from metrics run %s' % run.id)
    return _RUN_MAP[key]


def capture_file(set_id, path, name='', run_id=None, parents=(), _self=cmd):
    """Add a structure file to a set by loading it into the peek object and capturing
    that. The one path for files, so a file and an object always yield the same entry."""
    if not os.path.isfile(path):
        raise SetInputError('no such file: %s' % path)
    clear_peek(_self=_self)
    try:
        blocks = []
        if path.lower().endswith(('.cif', '.mmcif')):
            with open(path, errors='replace') as handle:
                blocks = _split_cif_blocks(handle.read())
        if len(blocks) > 1:
            # A set export: one data block per chain. PyMOL would make one object per
            # block, so merge them the way staging does.
            _load_chains([(label, text) for label, text in blocks], PEEK, _self=_self)
        else:
            _self.load(path, PEEK, zoom=0, quiet=1)
    except SetInputError:
        raise
    except Exception as exc:
        raise SetInputError('could not read %s: %s' % (path, exc))
    if not _exists(PEEK, _self=_self):
        # `load` multiplexed into objects named after the file's own blocks.
        raise SetInputError('%s did not load as one object; is it a multi-block CIF'
                            ' with a single chain per block?' % path)
    try:
        return capture_object(set_id, PEEK, name=name or document.stem(path),
                              run_id=run_id, parents=parents, _self=_self)
    finally:
        clear_peek(_self=_self)


def capture_folder(set_id, folder, _self=cmd):
    """Every structure file in a folder, plus the sidecar's columns if it has one."""
    c = container()
    files, sidecar = document.scan_folder(folder)
    rows = document.read_sidecar(sidecar) if sidecar else {}
    known = {col['column'] for col in c.columns(set_id) if col.get('column')}
    extra = document.sidecar_columns(rows, known)
    if extra:
        c.declare_columns(set_id, [{'key': col, 'scope': 'object', 'dtype': dtype,
                                    'tool': 'import'} for col, dtype in extra])
    ids = []
    coltypes = {col['column']: col.get('dtype', 'float') for col in c.columns(set_id)
                if col.get('column')}
    for path in files:
        entry_name = document.stem(path)
        new_ids = capture_file(set_id, path, name=entry_name, _self=_self)
        ids.extend(new_ids)
        row = rows.get(entry_name)
        if row and new_ids:
            _apply_sidecar_row(c, new_ids[0], row, coltypes)
    # Sequence-only rows: in the sidecar but with no structure file.
    for entry_name, row in rows.items():
        if any(document.stem(p) == entry_name for p in files):
            continue
        try:
            seqs = json.loads(row.get('sequences') or '{}')
        except ValueError:
            seqs = {}
        eid = c.add_entry(set_id, entry_name, sequences=seqs)
        _apply_sidecar_row(c, eid, row, coltypes)
        ids.append(eid)
    return ids


def _apply_sidecar_row(c, entry_id, row, coltypes):
    fields = {}
    if row.get('starred', '') != '':
        fields['starred'] = int(document.coerce_sidecar_value('bool', row['starred']))
    if row.get('rejected', '') != '':
        fields['rejected'] = int(document.coerce_sidecar_value('bool', row['rejected']))
    for key in ('tags', 'note'):
        if row.get(key):
            fields[key] = row[key]
    if row.get('parents'):
        try:
            parents = json.loads(row['parents'])
        except ValueError:
            parents = [p for p in row['parents'].split('+') if p]
        if isinstance(parents, list):
            fields['parents'] = parents
    if fields:
        c.update_entry(entry_id, **fields)
    for col, dtype in coltypes.items():
        if col in row and row[col] != '':
            c.set_scalar(entry_id, col, document.coerce_sidecar_value(dtype, row[col]))


def capture_fasta(set_id, path, _self=cmd):
    c = container()
    return [c.add_entry(set_id, name, sequences={'A': seq})
            for name, seq in document.read_fasta(path)]


# -- Stage / unstage ------------------------------------------------------------------


def budget(set_row):
    if set_row.get('budget'):
        return int(set_row['budget'])
    raw = container().meta_get('stage_budget', None)
    try:
        return int(raw) if raw not in (None, '') else DEFAULT_BUDGET
    except ValueError:
        return DEFAULT_BUDGET


def _staged(c, set_id, _self=cmd):
    """Entries whose staged object still exists. A link to an object the user deleted
    is cleared here, so a ghost never counts against the budget or blocks a re-stage."""
    present = set(_self.get_names('all') or [])
    live = []
    for e in c.entries(set_id, where='e.staged_object IS NOT NULL'):
        if e['staged_object'] in present:
            live.append(e)
        else:
            c.update_entry(e['id'], staged_object=None, pinned=0, staged_by='')
    return live


def _free_object_name(name, _self=cmd):
    base = _legal(name, _self=_self)
    candidate, n = base, 1
    while _exists(candidate, _self=_self):
        n += 1
        candidate = '%s_%d' % (base, n)
    return candidate


def _ensure_group(group, _self=cmd):
    if group in (_self.get_names('public_group_objects') or []):
        return
    if _exists(group, _self=_self):
        raise SetNameConflict('%r is an object, not a group; rename the set or the object'
                              % group)
    _self.group(group, quiet=1)


# -- The shared target (#545) -----------------------------------------------------------
#
# A binder-design run holds its target fixed, so every entry carries the same target
# chain -- ONE blob (see `canonical_cif`) -- and staging six of them used to put six
# copies of it in the scene. Instead, an entry whose non-design chains are that one
# blob stages as its design chain(s) only, over a single `target_<set>` object in the
# set's group (see `target_name`), loaded once. Identity is decided by content hash, never assumed:
#
#   * the entry names its design chains, has at least one other chain, and
#   * its run HELD THE REST FIXED -- a design run, whose inputs name the `design_chain`
#     it generated against a given target. A fold predicts every chain, and its first
#     model to land cannot know the second will differ, so hash identity alone would
#     split one model of a Boltz run and stage the rest whole -- and
#   * every entry of its RUN holds the same blob for each of those other chains, and
#   * that is the blob the set's shared target already holds (or there is none yet), and
#   * no metric of the entry is tied to a non-design chain (a chain scalar, or a residue
#     array indexed on the target), because those could not be written back onto a
#     binder-only object -- such an entry is staged whole, so no metric is ever dropped.
#
# Anything else is staged whole, exactly as before (a fold predicts every chain, so its
# target differs per entry). The target is an Object, not an Entry: it is never counted
# against the budget, it goes into a .pse as a plain object, and it is removed when the
# last entry staged over it leaves the scene. Its record lives in the container
# (`Container.shared_target`), so a saved or recovered session keeps the link.


def target_name(group):
    """`target_<set>`, the shared target's object name.

    NOT `<set>_target`, which is what #545 first asked for: PyMOL resolves a selection
    word that names no object by UNIQUE PREFIX (`SelectGetInfoIter`) before it expands
    groups, so a lone `rfd3_a1_target` inside the group `rfd3_a1` made `hide rfd3_a1`,
    `color red, rfd3_a1` and `get_object_list('rfd3_a1')` act on the target alone and
    never reach the binders (measured). A name the group's name is not a prefix of
    cannot shadow it -- which `target_<set>` is not, for a set called `t`, `ta`,
    `target` or `target_t`, so those take the next prefix that is safe."""
    for prefix in ('target_', 'shared_', 'fixed_'):
        name = prefix + str(group)
        if not name.startswith(str(group)):
            return name
    return 'target_of_' + str(group)


def _target_record(c, set_id):
    record = c.shared_target(set_id)
    if record is None:
        return None
    record = dict(record)
    record['entries'] = [str(e) for e in record.get('entries') or ()]
    record['signature'] = [list(p) for p in record.get('signature') or ()]
    return record


def _chains_of_index(index):
    """Chain ids an array's `index` names: [[chain, resi], ...], or nested pairs."""
    out = set()
    for item in index or ():
        if isinstance(item, (list, tuple)) and len(item) == 2 and \
                not isinstance(item[0], (list, tuple)):
            out.add(str(item[0]))
        elif isinstance(item, (list, tuple)):
            out |= _chains_of_index(item)
    return out


def _metrics_touch_other_chains(c, entry, designed):
    """True when a metric of `entry` is tied to a chain outside `designed`."""
    designed = {str(ch) for ch in designed}
    scalars = entry.get('scalars') or {}
    for col in c.columns(entry['set_id']):
        chain = col.get('chain')
        if col.get('column') and chain not in (None, '') and str(chain) not in designed \
                and scalars.get(col['column']) is not None:
            return True
    for row in c.arrays_of(entry['id']):
        chain = row.get('chain')
        if chain not in (None, '') and str(chain) not in designed:
            return True
        if _chains_of_index(row.get('index')) - designed:
            return True
    return False


def split_plan(c, entry):
    """(design chains, target signature) when `entry` may stage as its design chains
    over the set's shared target, else None. See the block comment above."""
    designed = [str(ch) for ch in entry.get('design_chains') or ()]
    if not designed:
        return None
    held = c.chain_blobs(entry['id'])
    chains = [ch for ch, _ in held]
    if not set(designed) <= set(chains):
        return None
    signature = sorted([ch, h] for ch, h in held if ch not in designed)
    if not signature:
        return None
    if not entry.get('run_id'):
        return None
    try:
        inputs = c.run(entry['run_id']).get('inputs') or {}
    except Exception:
        return None
    if not isinstance(inputs, dict) or not inputs.get('design_chain'):
        return None
    per_chain = c.run_chain_blobs(entry['run_id'], [ch for ch, _ in signature])
    if any(len(hashes) != 1 for hashes in per_chain.values()):
        return None
    record = _target_record(c, entry['set_id'])
    if record is not None and record['entries'] and record['signature'] != signature:
        return None
    if _metrics_touch_other_chains(c, entry, designed):
        return None
    return designed, signature


def _chains_sel(obj, chains):
    return '(%s) and (%s)' % (obj, ' or '.join('chain %s' % (ch if ch else '""')
                                               for ch in chains))


def _show_target(target, set_row=None, _self=cmd):
    """The shared target's look, the same whichever path made it (#545 review): a
    cartoon, with ligands as sticks. A delivered design has its own target copy hidden
    (`designing._hide_target_copy`), so a target made from one would otherwise inherit
    "hidden" -- and one made by `stage` would not.

    When it COINCIDES with the set's reference -- the user's own target, on screen, same
    chain sequences and within `COINCIDE_RMSD` on CA -- it is made DISABLED (round 2):
    drawing it would draw the same structure twice. Disabled rather than repless, so
    the object panel's toggle still does something: switch it on and the cartoon is
    there."""
    try:
        _self.hide('everything', target)
        _self.show('cartoon', target)
        _self.show('sticks', '(%s) and organic' % target)
    except Exception:
        pass
    try:
        if set_row is not None and _coincides_with_reference(target, set_row, _self=_self):
            _self.disable(target)
        else:
            _self.enable(target)
    except Exception:
        pass


#: CA RMSD (A) under which the shared target is the reference drawn a second time.
COINCIDE_RMSD = 0.5


def _polymer_sequences(sel, _self=cmd):
    chains = {}
    try:
        _self.iterate('(%s) and polymer and name CA' % sel,
                      'chains.setdefault(chain, []).append(resn)',
                      space={'chains': chains})
    except Exception:
        return None
    return [chains[ch] for ch in sorted(chains)]


def _coincides_with_reference(target, set_row, _self=cmd):
    """True when the set's reference is in the scene and the target is the same
    structure in the same place: equal per-chain residue sequences (chains in id
    order) and CA RMSD at most `COINCIDE_RMSD`, as they sit now."""
    ref = set_row.get('reference') or ''
    if not ref or ref == target or not _exists(ref, _self=_self):
        return False
    seq_t = _polymer_sequences(target, _self=_self)
    seq_r = _polymer_sequences(ref, _self=_self)
    if not seq_t or seq_t != seq_r:
        return False
    try:
        a = _self.get_coords('(%s) and polymer and name CA' % target, 1)
        b = _self.get_coords('(%s) and polymer and name CA' % ref,
                             max(1, int(_self.get_state() or 1)))
        if a is None or b is None or len(a) != len(b) or not len(a):
            return False
        # Ordered by chain id for both, as `_polymer_sequences` compared them.
        order_t = []
        order_r = []
        _self.iterate('(%s) and polymer and name CA' % target, 'L.append(chain)',
                      space={'L': order_t})
        _self.iterate('(%s) and polymer and name CA' % ref, 'L.append(chain)',
                      space={'L': order_r})
        ia = sorted(range(len(order_t)), key=lambda i: (order_t[i], i))
        ib = sorted(range(len(order_r)), key=lambda i: (order_r[i], i))
        total = sum(sum((a[i][k] - b[j][k]) ** 2 for k in range(3))
                    for i, j in zip(ia, ib))
        return (total / len(ia)) ** 0.5 <= COINCIDE_RMSD
    except Exception:
        return False


def _fit_onto_target(obj, target, designed, _self=cmd):
    """Move the whole complex in `obj` so its non-design chains lie on the shared
    target. Their atoms are the target's, blob for blob, so the fit is exact: the binder
    lands where its own complex puts it relative to THIS target, wherever the target
    or the reference has been moved since (#545 review). False when it cannot."""
    mobile = '(%s) and not (%s)' % (obj, _chains_sel(obj, designed))
    try:
        # Every target atom must have its twin in the complex (same identifiers): a
        # target the user re-chained or edited matches only part of it, and `fit`
        # over a part -- or over nothing, which it does not raise for -- places the
        # binder wrong (round 2). Refused, so the caller falls back.
        n_target = _self.count_atoms(target)
        matched = _self.count_atoms('(%s) in (%s)' % (mobile, target))
        if not n_target or matched != n_target or \
                _self.count_atoms(mobile) != n_target:
            raise SetInputError('%d of %d target atoms have a twin in the complex'
                                % (matched, n_target))
        _self.fit(mobile, target, mobile_state=0, target_state=1, quiet=1)
        return True
    except Exception as exc:
        colorprinting.warning(' sets: could not fit %s onto %s (%s)' % (obj, target, exc))
        return False


def _live_users(c, set_id, record, exclude=(), _self=cmd):
    """Entries named by the target record that are still staged, with their object in
    the scene."""
    users = set(record.get('entries') or ()) - set(exclude)
    if not users:
        return []
    return [e for e in c.entries(set_id, where='e.staged_object IS NOT NULL')
            if e['id'] in users and _exists(e['staged_object'], _self=_self)]


def _complex_on_binder(c, entry, binder, name, _self=cmd):
    """Load `entry`'s stored complex into `name`, placed by fitting its design chains
    onto `binder` -- the entry's staged object, which holds exactly those atoms -- so
    the complex sits where the scene says it does. True when the fit held."""
    _load_entry_into(c, entry, name, _self=_self)
    designed = [str(ch) for ch in entry.get('design_chains') or ()]
    try:
        _self.fit(_chains_sel(name, designed), binder, quiet=1)
        return True
    except Exception as exc:
        colorprinting.warning(' sets: could not place %s on %s (%s)' % (entry['name'],
                                                                         binder, exc))
        return False


def _rebuild_target(c, set_row, record, survivor, _self=cmd):
    """Recreate a shared target the user deleted while binders are still staged over
    it: from a SURVIVOR's stored complex, fit onto that survivor's staged binder (round
    2). The survivors keep their places; a target rebuilt from the new complex
    superposed on the reference could land anywhere relative to them."""
    temp = _self.get_unused_name('_raymol_rebuild')
    try:
        if not _complex_on_binder(c, survivor, survivor['staged_object'], temp,
                                  _self=_self):
            return ''
        designed = [str(ch) for ch in survivor.get('design_chains') or ()]
        _make_target(c, set_row, record['object'], temp, designed, state=1, _self=_self)
        return record['object']
    finally:
        if _exists(temp, _self=_self):
            _self.delete(temp)


def _make_target(c, set_row, target, source, designed, state=1, _self=cmd):
    """Create `target` from `source`'s non-design chains, give it the target look and
    put it in the set's group. Removes it again if any step fails."""
    group = set_row.get('group_name') or set_row['name']
    _self.create(target, '(%s) and not (%s)' % (source, _chains_sel(source, designed)),
                 source_state=state, target_state=1, zoom=0, quiet=1)
    try:
        if group in (_self.get_names('public_group_objects') or []):
            try:
                _self.group(group, target, 'add', quiet=1)
            except Exception as exc:
                colorprinting.warning(' sets: could not add %s to group %s (%s)'
                                      % (target, group, exc))
        _show_target(target, set_row, _self=_self)
    except Exception:
        if _exists(target, _self=_self):
            _self.delete(target)
        raise
    return target


def _restore_whole(c, entry, obj, set_row, _self=cmd):
    """Put `entry`'s whole complex back in `obj` after a failed split, where the scene
    had it: the stored complex, fit onto what `obj` still holds."""
    temp = _self.get_unused_name('_raymol_restore')
    try:
        _complex_on_binder(c, entry, obj, temp, _self=_self)
        group = set_row.get('group_name') or set_row['name']
        _self.delete(obj)
        _self.set_name(temp, obj)
        if group in (_self.get_names('public_group_objects') or []):
            _self.group(group, obj, 'add', quiet=1)
    except Exception as exc:
        colorprinting.warning(' sets: could not restore %s whole (%s)' % (obj, exc))
    finally:
        if _exists(temp, _self=_self):
            _self.delete(temp)


def place(c, set_row, entry, obj, superpose=True, allow_split=True,
          by=schema.STAGED_AUTO, _self=cmd):
    """Place a whole complex that was just loaded (or delivered) as `entry`'s staged
    object, link it, and -- when `split_plan` allows -- reduce it to its design chains
    over the set's shared target. Returns the plan, or None when staged whole.

    Placement: over an existing shared target, the complex is FIT onto it by its target
    chains; otherwise it is superposed onto the reference when `superpose` (what
    staging always did), and a target made now is made from it. One rule for `stage` and
    for batch delivery, so a set never mixes placements. A target the user deleted while
    binders are still staged over it is first rebuilt from one of them.

    If anything fails once the split has begun, the target made for it is removed and
    `obj` is put back whole, so nothing is left orphaned or half-reduced.

    `by` is recorded as the entry's `staged_by` (#546): 'auto' for a batch delivery,
    which a finished run may replace, 'user' for `set_stage`."""
    plan = split_plan(c, entry) if allow_split else None
    record = _target_record(c, set_row['id'])
    existing = record['object'] if record else ''
    created = ''
    if plan and existing and not _exists(existing, _self=_self):
        survivors = _live_users(c, set_row['id'], record, exclude=(entry['id'],),
                                _self=_self)
        if survivors:
            # The MOST RECENTLY staged survivor: `_adopt_target` appends, and if the
            # user moved the target by hand the later binders are the ones fit to
            # where it was last.
            order = {e: i for i, e in enumerate(record['entries'])}
            latest = max(survivors, key=lambda e: order.get(e['id'], -1))
            created = _rebuild_target(c, set_row, record, latest, _self=_self)
    fitted = False
    if plan and existing and _exists(existing, _self=_self):
        fitted = _fit_onto_target(obj, existing, plan[0], _self=_self)
        if not fitted:
            colorprinting.warning(' sets: %s is superposed on the reference instead, and'
                                  ' staged whole' % obj)
            plan = None                          # it cannot share a target it cannot fit
    if not fitted and superpose and set_row.get('reference'):
        _superpose(obj, set_row['reference'], _self=_self,
                   ref_sel=_reference_selection(c, set_row, _self=_self))
    reduced = False
    try:
        target = ''
        if plan:
            target, made = _share_target(c, set_row, obj, plan, _self=_self)
            created = created or made
            reduced = True
        c.update_entry(entry['id'], staged_object=obj, staged_by=by)
        if plan:
            _adopt_target(c, set_row, entry['id'], target, plan[1])
    except Exception:
        if created and _exists(created, _self=_self) and \
                not _live_users(c, set_row['id'], _target_record(c, set_row['id']) or {},
                                exclude=(entry['id'],), _self=_self):
            try:
                _self.delete(created)
            except Exception:
                pass
        if reduced and _exists(obj, _self=_self):
            _restore_whole(c, entry, obj, set_row, _self=_self)
        raise
    if by == schema.STAGED_AUTO:
        _remember_provisional(entry['id'], obj, _self=_self)
    return plan


def _share_target(c, set_row, obj, plan, _self=cmd):
    """Reduce the whole complex in `obj` to its design chains, putting the rest in the
    set's shared target (made from `obj`'s own atoms, so it sits exactly where this
    complex was placed, when there is none yet). Returns (target, the name if it was
    created here else '').

    The removal from `obj` is the LAST step, so a failure anywhere leaves `obj` whole;
    and a target made here is deleted again if that removal fails (round 2).

    The entry's link and the target's user list are written by the caller AFTER this
    returns, and the target object exists before its record names it: a `delete` in
    here runs `reconcile`, which must never see a record with no live user."""
    designed, signature = plan
    group = set_row.get('group_name') or set_row['name']
    record = _target_record(c, set_row['id'])
    target = record['object'] if record else ''
    created = ''
    if not target or not _exists(target, _self=_self):
        # A record whose object the user deleted gets it back under the same name.
        target = target or _free_object_name(target_name(group), _self=_self)
        state = max(1, int(_self.count_states(obj) or 1))
        _make_target(c, set_row, target, obj, designed, state=state, _self=_self)
        created = target
    try:
        _self.remove('(%s) and not (%s)' % (obj, _chains_sel(obj, designed)))
    except Exception:
        if created and _exists(created, _self=_self):
            _self.delete(created)
        raise
    return target, created


def _adopt_target(c, set_row, entry_id, target, signature):
    record = _target_record(c, set_row['id']) or {'entries': []}
    users = [e for e in record['entries'] if e != entry_id] + [entry_id]
    c.set_shared_target(set_row['id'], {'object': target, 'signature': signature,
                                        'entries': users})


def _settle_target(c, set_id, _self=cmd):
    """Drop users of the set's shared target that are no longer staged; when none is
    left, delete the target object and its record. Links are read as `_staged` leaves
    them, so call it after that."""
    record = _target_record(c, set_id)
    if record is None:
        return
    staged = {e['id'] for e in c.entries(set_id, where='e.staged_object IS NOT NULL')}
    users = [e for e in record['entries'] if e in staged]
    if users == record['entries']:
        return
    if users:
        c.set_shared_target(set_id, dict(record, entries=users))
        return
    c.set_shared_target(set_id, None)
    target = record['object']
    if _exists(target, _self=_self):
        try:
            mstore.forget_object(target)
        except Exception:
            pass
        _self.delete(target)


def shared_target_object(c, set_id, _self=cmd):
    """The set's shared target object's name when it is in the scene, else ''."""
    record = _target_record(c, set_id)
    if record and record['entries'] and _exists(record['object'], _self=_self):
        return record['object']
    return ''


def _split_info(obj, _self=cmd):
    """(container, set id, entry, record) when `obj` is a staged entry shown as its
    design chains over its set's shared target -- whether or not the target object is
    still in the scene -- else None."""
    try:
        if not obj or not store.is_open():
            return None
        c = container()
        targets = c.shared_targets()
        for set_id, record in targets.items():
            users = set(str(e) for e in record.get('entries') or ())
            for e in c.entries(set_id, where='e.staged_object = ?', params=(str(obj),)):
                if e['id'] in users:
                    return c, set_id, e, record
    except Exception:
        return None
    return None


def split_context(obj, _self=cmd):
    """The shared target object when `obj` is a staged entry shown as its design chains
    over it and that target is in the scene, else ''."""
    info = _split_info(obj, _self=_self)
    if info and _exists(info[3].get('object'), _self=_self):
        return info[3]['object']
    return ''


def is_split(obj, _self=cmd):
    """True when `obj` is a staged binder shown over a shared target (present or not):
    what an object-level tool (`set_add`, `predict`, `design_sequences`) asks before
    reading `obj` as if it were the whole complex."""
    return _split_info(obj, _self=_self) is not None


@contextlib.contextmanager
def complex_of(obj, state=1, _self=cmd):
    """`(name, state)` to read `obj` from AS THE WHOLE COMPLEX.

    For a staged binder shown over a shared target that is a hidden scratch object,
    deleted on exit, holding the entry's chains IN ITS STORED ORDER (round 2: a merge of
    two objects follows their object-list order, which differed between delivered and
    restaged binders) with the coordinates the scene has -- the binder's `state`, and
    the target as it sits. When the target object is gone, the stored complex is fit
    onto the binder instead (round 2), so a tool never silently reads half of it. For
    anything else it is `(obj, state)` itself, untouched."""
    info = _split_info(obj, _self=_self)
    if info is None:
        yield obj, state
        return
    c, _set_id, entry, record = info
    scratch = _self.get_unused_name('_raymol_complex')
    try:
        target = record.get('object') or ''
        designed = {str(ch) for ch in entry.get('design_chains') or ()}
        if target and _exists(target, _self=_self):
            texts = []
            for ch, _hash in c.chain_blobs(entry['id']):
                source, src_state = (obj, int(state)) if ch in designed else (target, 1)
                text = _self.get_cifstr(_chain_sel(source, ch), src_state)
                if text and text.strip():
                    texts.append((ch, text))
            _load_chains(texts, scratch, _self=_self)
        else:
            colorprinting.warning(' sets: %s is staged over a shared target that is not in'
                                  ' the scene; reading its stored complex' % obj)
            _complex_on_binder(c, entry, obj, scratch, _self=_self)
        _self.disable(scratch)
        yield scratch, 1
    finally:
        if _exists(scratch, _self=_self):
            _self.delete(scratch)


def complex_sources(obj, _self=cmd):
    """{chain: object it is read from in the scene} for `complex_of(obj)`: the design
    chains from `obj`, the rest from the shared target (or `obj` when it is gone)."""
    info = _split_info(obj, _self=_self)
    if info is None:
        return {}
    c, _set_id, entry, record = info
    designed = {str(ch) for ch in entry.get('design_chains') or ()}
    target = record.get('object') or ''
    if not _exists(target, _self=_self):
        target = obj
    return {ch: (obj if ch in designed else target) for ch, _ in c.chain_blobs(entry['id'])}


def _reference_selection(c, set_row, _self=cmd):
    """What to superpose onto: the reference, plus the shared target when the reference
    is an entry staged as its design chains over it (it holds only a binder)."""
    ref = set_row.get('reference') or ''
    record = _target_record(c, set_row['id'])
    if not ref or record is None or not _exists(record['object'], _self=_self):
        return None
    users = set(record['entries'])
    if any(e['staged_object'] == ref and e['id'] in users
           for e in c.entries(set_row['id'], where='e.staged_object IS NOT NULL')):
        return '(%s) or (%s)' % (ref, record['object'])
    return None


def _write_back_metrics(c, entry, obj, _self=cmd):
    """The entry's columns and arrays as metrics-store runs on the staged object, one run
    per tool this build declares. Undeclared tools and keys are skipped: the numbers stay
    in the set, they just cannot colour an object here."""
    columns = c.columns(entry['set_id'])
    array_tool = {col.get('key'): col.get('tool') or '' for col in columns
                  if not col.get('column')}
    by_tool = {}
    for col in columns:
        if not col.get('column'):
            continue                      # an array declaration; handled below
        tool = col.get('tool') or ''
        key = col.get('key') or col['column']
        if not tool or _spec_or_none(tool, key) is None:
            continue
        value = (entry.get('scalars') or {}).get(col['column'])
        if value is None:
            continue
        kw = {}
        if col.get('scope', 'object') == 'state':
            kw['state'] = 1
        if col.get('chain'):
            kw['chain'] = col['chain']
        by_tool.setdefault(tool, []).append(mstore.value(tool, key, value=value, **kw))
    for row in c.arrays_of(entry['id']):
        tool = array_tool.get(row['key'], '')
        if not tool or _spec_or_none(tool, row['key']) is None:
            continue
        index, values = c.array(entry['id'], row['key'], chain=row.get('chain'))
        kw = {'state': 1, 'index': [tuple(p) for p in index], 'values': values}
        if row.get('chain'):
            kw['chain'] = row['chain']
        by_tool.setdefault(tool, []).append(mstore.value(tool, row['key'], **kw))
    for tool, values in by_tool.items():
        try:
            mbinding.record(obj, tool, values, inputs={'set': entry['set_id'],
                                                       'entry': entry['name']},
                            _self=_self)
        except Exception as exc:
            colorprinting.warning(' sets: metrics for %s (%s) not written: %s'
                                  % (obj, tool, exc))


def _load_entry_into(c, entry, obj, _self=cmd):
    chains = c.chain_cifs(entry['id'])
    if not chains:
        raise SetInputError('%s has no structure to show' % entry['name'])
    _load_chains(chains, obj, _self=_self)
    try:
        _self.dss(obj)
    except Exception:
        pass


def stage(set_row, entries, budget_override=None, by=schema.STAGED_USER, _self=cmd):
    """Load entries as objects in the set's group. Returns the object names.

    Refuses past the budget with the unpinned staged names it would need to drop; it
    never drops them itself. An entry already staged is left alone and its object name
    returned -- but staged BY the caller from now on (#546): `set_stage` on a
    provisional entry is the user keeping it, so a finished run may no longer replace
    it. `by` is 'user' for every caller but the end-of-run restage.
    """
    c = container()
    set_id = set_row['id']
    staged = _staged(c, set_id, _self=_self)
    _settle_target(c, set_id, _self=_self)      # a record naming only dead links
    already = {e['id'] for e in staged}
    todo = [e for e in entries if e['id'] not in already]
    limit = int(budget_override) if budget_override else budget(set_row)
    if len(staged) + len(todo) > limit:
        unpinned = [e['name'] for e in staged if not e.get('pinned')]
        raise SetBudgetExceeded(
            'staging %d more would put %d objects in the scene; the budget is %d.'
            ' Unstage some of: %s (or raise the budget with set_budget)'
            % (len(todo), len(staged) + len(todo), limit,
               ', '.join(unpinned) or 'nothing is unpinned'), unpinned=unpinned)
    names = [e['staged_object'] for e in entries if e['id'] in already]
    live = {e['id']: e for e in staged}
    for e in entries:
        if e['id'] in already and live[e['id']].get('staged_by') != by:
            c.update_entry(e['id'], staged_by=by)
    if not todo:
        return names
    group = set_row.get('group_name') or set_row['name']
    # Staged into an EMPTY scene -- after a recovery that brought the sets back without
    # the scene, typically -- the camera is still wherever the empty session left it,
    # and a design sitting at its target's coordinates is off-screen: a black viewport
    # with the objects listed beside it (#547 review, measured: get_view unchanged by a
    # stage). So only then, the camera goes to what was staged. With anything else in
    # the scene the camera is the user's and is never moved.
    was_empty = not (_self.get_names('public_nongroup_objects') or [])
    _ensure_group(group, _self=_self)
    for e in todo:
        obj = _free_object_name(e['name'], _self=_self)
        # Whole first, placed as a whole (fit onto the shared target, or superposed on
        # the reference), and only THEN reduced to its design chains, so a binder staged
        # over the shared target sits where its own complex puts it relative to it.
        _load_entry_into(c, e, obj, _self=_self)
        try:
            _self.group(group, obj, 'add', quiet=1)
        except Exception as exc:
            colorprinting.warning(' sets: could not add %s to group %s (%s)' % (obj, group, exc))
        place(c, set_row, e, obj, superpose=True, by=by, _self=_self)
        _write_back_metrics(c, dict(e, staged_object=obj), obj, _self=_self)
        names.append(obj)
    if was_empty and names:
        try:
            _self.zoom(group, animate=0)
        except Exception:
            pass
    return names


def pick_to_fit(c, set_row, entries, _self=cmd):
    """`entries` cut to the set's FREE stage slots, best first: `(chosen, label)`.

    All of them, with label '', when they fit. Otherwise the top `free` by the set's
    ranking -- the key a finished run restages by (`_ranking`: its own ranking key,
    else its tool's declared metric), with that key's label -- and, when there is none,
    the first `free` in delivery order, with label ''. What "Stage top K starred" stages
    after a recovery (#547 review): sixteen stars and a budget of six must not leave
    the one staging action greyed out."""
    entries = list(entries)
    free = max(budget(set_row) - len(_staged(c, set_row['id'], _self=_self)), 0)
    if len(entries) <= free:
        return entries, ''
    ranking = _ranking(c, set_row)
    label = ''
    if ranking is not None:
        key, desc, label = ranking

        def order(e):
            value = (e.get('scalars') or {}).get(key)
            if value is None:
                return (1, 0, e.get('ord') or 0)
            return (0, -value if desc else value, e.get('ord') or 0)
    else:
        def order(e):
            return (0, 0, e.get('ord') or 0)
    return sorted(entries, key=order)[:free], label


def stageable_starred(c, set_row):
    """Starred entries a stage could still add: unstaged, with a stored structure --
    the ones the drawer's "Stage N starred" counts."""
    return c.entries(set_row['id'], where='e.starred = 1 AND e.staged_object IS NULL'
                                          ' AND ' + HAS_STRUCTURE)


def unstage(set_row, entries, include_pinned=False, by=schema.STAGED_USER, _self=cmd):
    """Delete the entries' objects and their metrics runs; clear the links. Pinned
    entries are skipped unless `include_pinned` (the caller named them explicitly).

    `by` is recorded on each entry unstaged (#546): 'user' means a person took it out,
    so a finished run's restage will not put it back; the restage itself passes ''."""
    c = container()
    removed = []
    for e in entries:
        obj = e.get('staged_object')
        if not obj:
            continue
        if e.get('pinned') and not include_pinned:
            continue
        if _exists(obj, _self=_self):
            try:
                mstore.forget_object(obj)
            except Exception:
                pass
            _self.delete(obj)
            removed.append(obj)
        c.update_entry(e['id'], staged_object=None, pinned=0, staged_by=by)
        _PROVISIONAL.pop(e['id'], None)
    _settle_target(c, set_row['id'], _self=_self)
    _drop_empty_group(set_row, _self=_self)
    return removed


#: entry id -> (object name, fingerprint) for every PROVISIONAL stage this process
#: made (#546 review). What lets a restage tell "the batch put this here and nobody
#: has touched it" from "the user has been working on it": an edit of any kind
#: (`alter`, `remove`, a mutation, a repack) changes the fingerprint, and an entry
#: whose object was edited is the user's. In memory on purpose: a restage only
#: happens in the process whose batch staged the entry, and an entry with no record
#: here counts as edited -- the safe side.
_PROVISIONAL = {}


def _fingerprint(obj, _self=cmd):
    """A cheap digest of what an edit changes: every atom's identity, element, B, q
    and charge, and the coordinates of the displayed state. Not colours or
    representations -- the app colours delivered designs itself -- and not the object
    matrix, which a view drag moves without editing anything."""
    import hashlib
    atoms = []
    try:
        _self.iterate(obj, 'atoms.append((chain, resi, resn, name, elem, b, q,'
                      ' formal_charge))', space={'atoms': atoms})
        coords = _self.get_coords(obj, state=-1)
    except Exception:
        return ''
    digest = hashlib.sha1(repr(atoms).encode('utf-8'))
    if coords is not None:
        digest.update(coords.round(3).tobytes())
    return digest.hexdigest()


def _remember_provisional(entry_id, obj, _self=cmd):
    _PROVISIONAL[entry_id] = (obj, _fingerprint(obj, _self=_self))


def _edited(entry, _self=cmd):
    """True when a provisional entry's object is not the one its stage left: renamed,
    edited, or staged before this process could fingerprint it."""
    record = _PROVISIONAL.get(entry['id'])
    obj = entry.get('staged_object')
    if record is None or record[0] != obj:
        return True
    return _fingerprint(obj, _self=_self) != record[1]


def _tool_ranking_keys(tool):
    """The ranking metrics a tool DECLARES (`ranking_metrics` on its Predictor or
    Generator class), in preference order; () when it declares none or is unknown."""
    if not tool:
        return ()
    for module in ('pymol.predictors.registry', 'pymol.generators.registry'):
        try:
            registry = __import__(module, fromlist=['get'])
            return tuple(getattr(registry.get(tool), 'ranking_metrics', ()) or ())
        except Exception:
            continue
    return ()


#: An entry with a STRUCTURE to stage: a stored chain. Not `n_chains`, which counts the
#: chains of a sequence-only entry too.
HAS_STRUCTURE = 'EXISTS (SELECT 1 FROM chains ch WHERE ch.entry_id = e.id)'


def _candidates_sql(c, set_row, column):
    """(where, params) for the entries a restage may put in the scene, ranked on
    `column`: a value for it, not rejected, a structure, past the active filter (the
    rows `top:N` reads), and not taken out by a person."""
    from . import filter as _filter, selectors
    columns = selectors._columns_map(c, set_row['id'])
    where, params = _filter.compile(set_row.get('filter') or '', columns)
    clauses = ['%s IS NOT NULL' % column, 'e.rejected = 0', HAS_STRUCTURE,
               'NOT (e.staged_by = ? AND e.staged_object IS NULL)']
    params = list(params) + [schema.STAGED_USER]
    if where:
        clauses.insert(0, '(%s)' % where)
    return ' AND '.join(clauses), tuple(params)


def _ranking(c, set_row):
    """(column, descending, label) to restage by, or None (#546 review).

    Which key: the set's own ranking key when it has one (the user sorted on it);
    otherwise the first of its tool's declared `ranking_metrics` that is a column here.
    The tool's key is USED, not written into `ranking_key`, so `top:N`, the histogram and
    the sort indicator stay what the user made them.

    Which direction: the column's `higher_is_better`. An ascending click on the header
    is a way of LOOKING at the worst, not a statement that low pLDDT is good. Only a
    column that declares no direction falls back to the sort -- and only for the set's
    own key; a tool key with no direction is not a ranking.

    Only when it separates anything: at least two distinct values among the
    candidates. Ties everywhere (a backbone-validity score of 100 for every design)
    would announce a restage that ranked nothing."""
    columns = {col.get('column'): col for col in c.columns(set_row['id'])
               if col.get('column')}
    own = set_row.get('ranking_key') or ''
    choices = []
    if own in columns:
        choices.append((own, True))
    else:
        choices.extend((k, False) for k in _tool_ranking_keys(set_row.get('tool'))
                       if k in columns)
    for key, is_own in choices:
        spec = columns[key]
        better = spec.get('higher_is_better')
        if better is None:
            if not is_own or (set_row.get('sort_key') or '') != key:
                continue
            desc = bool(int(set_row.get('sort_desc') or 0))
        else:
            desc = bool(better)
        column = 'm.%s' % schema.quote(key)
        where, params = _candidates_sql(c, set_row, column)
        if c.distinct_count(set_row['id'], column, where, params) < 2:
            if is_own:
                return None
            continue
        return key, desc, spec.get('label') or key
    return None


def restage_by_ranking(set_row, _self=cmd):
    """When a run finishes (#546): replace the set's PROVISIONAL staging with its top
    entries by ranking key. Returns `{'staged', 'unstaged', 'top', 'kept', 'key',
    'label', 'text'}`, or None when there is nothing to rank by (see `_ranking`), in
    which case the provisional staging stays as it is.

    The rule, in order:
      * pinned entries, ones a person staged (`staged_by` other than 'auto') and
        provisional ones whose object was EDITED since it was staged are never
        touched; an edited one becomes the user's. They are charged to the budget
        first;
      * the slots left (`budget - kept`, never negative) go to the best candidates by
        the ranking key (`_candidates_sql`);
      * slots the ranking cannot fill -- too few entries have a value yet -- keep the
        provisional entries already there, in arrival order, so an unscored design
        is displaced only by a ranked one and the scene never shrinks for want of a
        score;
      * the provisional entries left over are unstaged.

    The whole SET is ranked, not just the run that finished: an extending run's
    designs compete with the earlier run's provisional ones.

    Stage first, then unstage: while the new entries go in, the old ones are still
    users of the shared target (#545), so it is never deleted and remade in between.
    If staging fails part-way, only as many displaced entries are unstaged as the
    budget needs, so the set is never left over budget and never emptier than asked.
    """
    c = container()
    set_row = c.get_set(set_row['id'])
    if (set_row.get('kind') or 'structures') != 'structures':
        return None
    ranking = _ranking(c, set_row)
    if ranking is None:
        return None
    key, desc, label = ranking
    set_id = set_row['id']
    column = 'm.%s' % schema.quote(key)
    staged = _staged(c, set_id, _self=_self)
    _settle_target(c, set_id, _self=_self)
    kept, provisional = [], []
    for e in staged:
        if e.get('pinned') or e.get('staged_by') != schema.STAGED_AUTO:
            kept.append(e)
        elif _edited(e, _self=_self):
            c.update_entry(e['id'], staged_by=schema.STAGED_USER)
            kept.append(e)
        else:
            provisional.append(e)
    kept_ids = {e['id'] for e in kept}
    limit = budget(set_row)
    slots = max(limit - len(kept), 0)

    from . import selectors
    where, params = _candidates_sql(c, set_row, column)
    order = selectors._order(dict(set_row, sort_key=key, sort_desc=1 if desc else 0),
                             selectors._columns_map(c, set_id))
    top = []
    if slots:
        # `kept` entries can rank anywhere, so ask for enough rows to skip past them.
        for e in c.entries(set_id, where=where, params=params, order_by=order,
                           limit=slots + len(kept)):
            if e['id'] in kept_ids:
                continue
            top.append(e)
            if len(top) == slots:
                break
    top_ids = {e['id'] for e in top}
    # Slots the ranking left empty keep the UNSCORED provisional entries already
    # there, oldest first.
    def value(e):
        return (e.get('scalars') or {}).get(key)

    filler = [e for e in sorted(provisional, key=lambda e: e.get('ord') or 0)
              if e['id'] not in top_ids and value(e) is None][:max(slots - len(top), 0)]
    stay = top_ids | {e['id'] for e in filler}
    to_stage = [e for e in top if not e.get('staged_object')]
    # Worst first -- unscored, then lowest-ranked -- so a partial swap gives up the
    # least valuable entries.
    to_drop = [e for e in provisional if e['id'] not in stay]
    to_drop.sort(key=lambda e: (value(e) is not None,
                                0 if value(e) is None else (value(e) if desc else -value(e))))
    result = {'staged': [], 'unstaged': [], 'top': len(top), 'kept': len(kept),
              'key': key, 'label': label, 'text': ''}
    if not to_stage and not to_drop:
        return result
    done = False
    try:
        if to_stage:
            result['staged'] = stage(set_row, to_stage,
                                     budget_override=len(staged) + len(to_stage),
                                     by=schema.STAGED_AUTO, _self=_self)
        done = True
    finally:
        drop = to_drop
        if not done:
            # Only what the budget needs: each new entry that made it in displaces one.
            live = len(_staged(c, set_id, _self=_self))
            excess = max(live - max(limit, len(kept)), 0)
            drop = to_drop[:excess]
        if drop:
            result['unstaged'] = unstage(set_row, drop, by='', _self=_self)
    text = 'Restaged top %d by %s' % (len(top), label)
    extra = []
    if kept:
        extra.append('%d pinned or staged by you kept' % len(kept))
    if filler:
        extra.append('%d not yet scored kept' % len(filler))
    if extra:
        text += ' (%s)' % '; '.join(extra)
    result['text'] = text
    return result


def _drop_empty_group(set_row, _self=cmd):
    group = set_row.get('group_name') or set_row['name']
    if group not in (_self.get_names('public_group_objects') or []):
        return
    if _staged(container(), set_row['id'], _self=_self):
        return
    children = _group_children(group, _self=_self)
    if children is None or children:
        return
    try:
        _self.delete(group)
    except Exception:
        pass


def on_objects_deleted(_self=cmd):
    """After `delete`: clear links whose object is gone, NOW, so a new object made
    under the same name is never mistaken for the entry that once bore it.

    A staged object deleted by hand is the user unstaging it (#546), so it is marked
    so first -- a finished run's restage must not bring back what was just deleted.
    `reconcile` alone (a session load) leaves `staged_by` neutral instead."""
    if store.is_open():
        c = container()
        present = set(_self.get_names('all') or [])
        for s in c.sets():
            for e in c.entries(s['id'], where='e.staged_object IS NOT NULL'):
                if e['staged_object'] not in present:
                    c.update_entry(e['id'], staged_object=None, pinned=0,
                                   staged_by=schema.STAGED_USER)
    reconcile(_self=_self)


def on_object_renamed(old, new, _self=cmd):
    """After `set_name`: a staged object keeps its link under the new name."""
    if not store.is_open() or not old or old == new:
        return
    c = container()
    for s in c.sets():
        for e in c.entries(s['id'], where='e.staged_object = ?', params=(old,)):
            c.update_entry(e['id'], staged_object=new)
    for set_id, record in c.shared_targets().items():
        if record.get('object') == old:
            c.set_shared_target(set_id, dict(record, object=new))


def reconcile(_self=cmd):
    """Clear links whose object is gone (deleted by the user, or absent from the session
    that was just loaded). Called after every session restore."""
    if not store.is_open():
        return
    c = container()
    targets = c.shared_targets()
    for s in c.sets():
        _staged(c, s['id'], _self=_self)
        if s['id'] in targets:
            _settle_target(c, s['id'], _self=_self)
    for set_id in set(targets) - {s['id'] for s in c.sets()}:
        c.set_shared_target(set_id, None)        # its set is gone


# -- Peek ------------------------------------------------------------------------------


def clear_peek(_self=cmd):
    if _exists(PEEK, _self=_self):
        _self.delete(PEEK)


def peek(set_row, entry, _self=cmd):
    """Show one entry in the peek object, replacing whatever it showed. Fixed look: a
    dim, half-transparent cartoon, so it cannot be mistaken for a staged object."""
    c = container()
    clear_peek(_self=_self)
    _load_entry_into(c, entry, PEEK, _self=_self)
    _superpose(PEEK, set_row.get('reference') or '', _self=_self,
               ref_sel=_reference_selection(c, set_row, _self=_self))
    # Only the designed chain(s) (#545): the target is already on screen, and a ghost
    # of it drawn over itself is 141 residues of noise around a 60-residue binder.
    # Superposed WHOLE first, so the binder lands where its complex puts it.
    # Only for an entry that WOULD stage over the shared target: a fold whose target
    # really differs is ghosted whole, target and all (#545 review).
    plan = split_plan(c, entry)
    designed = list(plan[0]) if plan else []
    if designed and set(designed) < set(_chains(PEEK, _self=_self)):
        _self.remove('(%s) and not (%s)' % (PEEK, _chains_sel(PEEK, designed)))
    try:
        _self.hide('everything', PEEK)
        _self.show('cartoon', PEEK)
        _self.color('grey70', PEEK)
        _self.set('cartoon_transparency', 0.5, PEEK)
    except Exception:
        pass
    return PEEK


# -- Session: .raymol save/load, .pse save/load ------------------------------------------


def _strip_peek(session):
    names = session.get('names')
    if isinstance(names, list):
        session['names'] = [entry for entry in names
                            if not (entry and entry[0] == PEEK)]


def session_save(session, _self=cmd, **_kwargs):
    """Session-save task. Keeps the peek object out of every session dictionary, so it
    can never come back from a .pse as a real object. Never touches the store."""
    _strip_peek(session)
    return 1


def warn_if_pse_leaves_sets(filename='', _self=cmd):
    """Called by `save` on the .pse/.psw path (not from the session task: `get_session`
    is also used for reads like the group-membership check, and a warning on every read
    would be noise). Names the sets a plain .pse leaves behind.

    A set whose EVERY entry is staged is not named: each of its structures is an object
    in the .pse, so nothing is lost -- and since #416 every single design has a
    one-entry set behind it, a warning there would fire on every save of every session
    that ever ran a design. Only the links and the columns stay behind, which is what the
    words say.
    """
    if _SAVING_RAYMOL or not store.is_open():
        return False
    try:
        c = container()
        names = [s['name'] for s in c.sets()
                 if c.count(s['id']) > c.count(s['id'], 'e.staged_object IS NOT NULL')]
        # A set whose binders are staged over a shared target that is no longer in the
        # scene is ALSO left behind: the .pse holds only the binders (#545 review).
        by_id = {s['id']: s['name'] for s in c.sets()}
        for set_id, record in c.shared_targets().items():
            if record.get('entries') and not _exists(record.get('object'), _self=_self) \
                    and by_id.get(set_id) and by_id[set_id] not in names:
                names.append(by_id[set_id])
    except Exception:
        return False
    if not names:
        return False
    colorprinting.warning(
        ' sets: a .pse cannot hold sets; %s left out. Use `save name.raymol` to keep'
        ' the whole session in one file.' % ', '.join(names))
    return True


def session_restore(session, _self=cmd, **_kwargs):
    """Session-restore task: drop links to staged objects the incoming session does not
    have. Never resets the store -- `set_session` also restores in-memory snapshots
    (the theme preview) and partial loads merge, so the reset for a bare `load x.pse`
    lives in `importing.load_pse`, which knows it is one."""
    try:
        reconcile(_self=_self)
    except Exception as exc:
        colorprinting.warning(' sets: could not reconcile staged objects: %s' % exc)
    return 1


def _app_version(_self=cmd):
    try:
        return str(_self.get_version()[0])
    except Exception:
        return ''


def _pse_bytes(_self=cmd):
    global _SAVING_RAYMOL
    _SAVING_RAYMOL = True
    try:
        session = _self.get_session('', 0, 1)      # session_save strips the peek

        return pickle.dumps(session, 1)
    finally:
        _SAVING_RAYMOL = False


def save_raymol(filename, quiet=1, _self=cmd):
    """`save x.raymol`. If the open container is already this file, write the session
    blob; otherwise copy the container there and continue on the copy.

    Ordered so that no failure loses data: the copy is made to a temporary beside the
    target, the target and any stale `-wal`/`-shm` of a crashed session are removed
    only when the copy exists, the previous file is deleted only after the new one is
    open and holds the session, and on any failure the previous container is reopened
    and reinstalled.
    """
    filename = os.path.abspath(_self.exp_path(filename))
    c = container()
    same = os.path.exists(filename) and os.path.samefile(filename, c.path)
    if not same and store.writers(filename):
        # The document a batch outlived its session in (#448): it is still writing
        # there, so saving over it would replace the campaign with this session.
        raise SetInputError(
            '%s is where %s is still writing its results (it was the document when the'
            ' session was replaced); save this session somewhere else, or load that file'
            ' to go back to it' % (filename, ', '.join(store.writers(filename))))
    if not same:
        old_path = c.path
        tmp = filename + '.saving'
        store.remove_db_files(tmp)
        try:
            moved = c.save_into(tmp)          # closes c
            moved.close()
            store.remove_db_files(filename)   # the target AND a stale WAL beside it
            os.replace(tmp, filename)
            c = store.replace(store.Container(filename))
        except Exception:
            store.remove_db_files(tmp)
            try:
                store.replace(store.Container(old_path))
            except Exception:
                pass
            raise
    try:
        c.write_session(_pse_bytes(_self=_self),
                        pse_version=_self.get_setting_float('pse_export_version'),
                        app_version=_app_version(_self=_self))
    except Exception as exc:
        raise SetInputError('could not write the session into %s: %s' % (filename, exc))
    if not same and (os.path.abspath(old_path) == os.path.abspath(store.working_path())
                     or store.is_preserved(old_path)):
        # force: the ONE place a non-empty working file may still be deleted (#447).
        # Everything in it was just copied into the document the user named, so
        # preserving it would offer them, on the next launch, a recovery of work they
        # explicitly saved -- and a second copy of every structure blob on disk.
        #
        # A PRESERVED container counts as a working file here (#447 review): Save As
        # from a recovered session is exactly the "now put it somewhere I chose" the
        # alert sends the user to, and leaving the recovered_ copy behind would offer
        # it back on the next launch, duplicate every structure blob, and make the
        # docs' "the next Save moves it where you want it" a lie.
        store.retire_working_file(old_path, force=True)
    _self.set('session_file', filename.replace('\\', '/'), quiet=1)
    if not int(quiet):
        colorprinting.parrot(' Save: wrote session and %d set(s) to %s'
                             % (len(c.sets()), filename))
    return _self.DEFAULT_SUCCESS


def checkpoint_session(_self=cmd):
    """Write the current session into the working container, so that what survives a
    quit carries the SCENE as well as the sets (#447, spec §2.1: "the working file for
    an untitled session IS the autosave").

    Called by the app on the way out, not on a timer: it pickles the whole session,
    which is the expensive half of a Save, and the cheap half (the entries) is already
    on disk the moment each result lands. A crash therefore still recovers the sets and
    loses the camera, which is the trade #415 already made everywhere else.

    A no-op unless there is something to protect: no container open (a session that
    never touched a set writes nothing anywhere), a real document open (⌘S is that
    session's answer, and writing behind the user's back is not), or a working file
    with no entries (it is deleted at exit, so a session blob in it is pure cost).
    Returns True when a blob was written.
    """
    if not store.is_open():
        return False
    c = store.active()
    if os.path.abspath(c.path) != os.path.abspath(store.working_path()):
        return False
    # A running batch keeps the file even before its first entry (#448), so it keeps
    # the scene too -- else reopening it says "Scene not recovered" and the target the
    # batch was designing against is gone (#448 review).
    if not c.holds_entries() and not store.writers(c.path):
        return False
    try:
        c.write_session(_pse_bytes(_self=_self),
                        pse_version=_self.get_setting_float('pse_export_version'),
                        app_version=_app_version(_self=_self))
    except Exception as exc:
        colorprinting.warning(' sets: could not checkpoint the session: %s' % exc)
        return False
    return True


def checkpoint_before_replace(_self=cmd):
    """`checkpoint_session` for the moment just BEFORE the scene is replaced (`load`,
    `reinitialize`), and never raising: an untitled session whose working file is about
    to be kept for recovery keeps its scene with it (#448), so reopening the recovered
    file brings back the staged designs and not only the table. Returns True when a
    blob was written."""
    try:
        return checkpoint_session(_self=_self)
    except Exception:
        return False


def _names(running, limit=3):
    names = list(dict.fromkeys(str(n) for n in running or ()))
    if len(names) > limit:
        return '%s and %d more' % (', '.join(names[:limit]), len(names) - limit)
    return ', '.join(names)


def _report_release(event, path=None, running=None, **_):
    """The one console line #448 asks for, whichever path replaced the session: what
    was kept, how many entries, where -- and which batch is still writing there."""
    if event == 'kept':
        sets = [(name, n) for name, n in store.describe_container(path) if n]
        total = sum(n for _, n in sets)
        what = ('%d entr%s in %s' % (total, 'y' if total == 1 else 'ies',
                                      _names([name for name, _ in sets]))
                if total else 'no entries yet')
        line = (' sets: the untitled session\'s sets were never saved, so they were'
                ' kept: %s, at %s. "load" that file to go back to them; it is also'
                ' offered at the next launch.' % (what, path))
        if running:
            line += (' Still running: %s -- its remaining results are written there'
                     ' too.' % _names(running))
        colorprinting.warning(line)
    elif event == 'left' and running:
        total = sum(n for _, n in store.describe_container(path))
        colorprinting.warning(
            ' sets: %s is still running; its remaining results are written to %s'
            ' (%d entr%s there now, no longer open), not to the session that replaced'
            ' it.' % (_names(running), path, total, 'y' if total == 1 else 'ies'))
    return None


store.observe(_report_release)


def _read_session_readonly(path):
    """The session blob of `path` read through a READ-ONLY connection, or None when
    there is none or the file cannot be read that way (the container's own open then
    says why)."""
    import sqlite3
    from urllib.request import pathname2url
    try:
        conn = sqlite3.connect('file:%s?mode=ro' % pathname2url(path), uri=True)
    except Exception:
        return None
    try:
        row = conn.execute('SELECT pse FROM session WHERE id = 1').fetchone()
        return bytes(row[0]) if row and row[0] is not None else None
    except Exception:
        return None
    finally:
        conn.close()


def load_raymol(filename, partial=0, quiet=1, *, _self=cmd):
    """`load x.raymol`. Opens the container IN PLACE, then restores the session blob it
    carries. Later results write straight into the document.

    Validates everything it can before it changes anything: the file opens as ours and
    its session blob unpickles first, then the scene is cleared or replaced, and only
    then is the document installed and the previous working file removed. A partial
    load is refused: it would merge the scene but there is no meaning to merging two
    documents' sets.
    """
    if int(partial):
        raise SetInputError('a .raymol cannot be loaded partially; export the session'
                            ' as .pse and load that partially instead')
    filename = os.path.abspath(_self.exp_path(filename))
    if not os.path.isfile(filename):
        raise SetInputError('no such file: %s' % filename)
    # The session blob is read and unpickled BEFORE the container is opened, because
    # opening migrates an older file in place (#545 review): a file whose session this
    # build cannot read is refused untouched, not refused after it was upgraded.
    store.about_to_open(filename)
    early = _read_session_readonly(filename)
    session = None
    if early is not None:
        try:
            session = pickle.loads(early)
        except Exception as exc:
            raise SetFormatError('%s carries a session this build cannot read: %s'
                                 % (filename, exc))
    new = store.Container(filename)          # SetFormatError if it is not ours
    if early is None:
        # The read-only look found no session (or could not look): ask the container,
        # which is the authority. Unpickled ONCE either way (#545 review round 2).
        try:
            blob = new.read_session()
            session = pickle.loads(blob) if blob else None
        except Exception as exc:
            new.close()
            raise SetFormatError('%s carries a session this build cannot read: %s'
                                 % (filename, exc))
    old = container()
    old_path = old.path
    if session is not None:
        # The scene goes with the working file if that file is about to be kept for
        # recovery (#448): `set_session` below replaces it, and a recovered container
        # without its scene opens as "Scene not recovered". A no-op for a document or
        # a working file with nothing in it. (With no session, `reinitialize` below
        # does this itself.)
        checkpoint_before_replace(_self=_self)
    if session is None:
        # A container written by the store alone (a batch that never saw Save, an
        # exported set) carries no session. Clear the scene FIRST: `reinitialize`
        # resets the store, which would close the document if it were installed.
        _self.reinitialize()
    store.replace(new)
    # A restage notice is about the run that just ended in THAT session; days later,
    # in another, it would describe nothing on screen (#546 review). A recovery notice
    # is the one kind that is about opening the file, and has its own rules (#547).
    for s in new.sets():
        if (new.notice(s['id']) or {}).get('kind') == 'restage':
            new.set_notice(s['id'], None)
    if session is not None:
        r = _self.set_session(session, quiet=quiet, partial=0, steal=1)
    else:
        r = _self.DEFAULT_SUCCESS
    reconcile(_self=_self)
    if os.path.abspath(old_path) == os.path.abspath(store.working_path()) \
            and os.path.abspath(old_path) != os.path.abspath(filename):
        # Not force: opening another document is not permission to discard what the
        # previous, untitled one holds. A batch that landed entries into the working
        # file keeps them, under a recovered_ name, and is offered back on the next
        # launch (#447); a batch still RUNNING keeps it even before its first result,
        # and its later results follow it there (#448). The console line is
        # `_report_release`'s, so this path and `reset()`'s say the same thing.
        store.release_working_file(old_path)
    _self.set('session_file', filename.replace('\\', '/'), quiet=1)
    if session is None and store.is_preserved(filename):
        try:
            after_recovery(_self=_self)
        except Exception as exc:
            colorprinting.warning(' sets: recovered, but could not point you at a set'
                                  ' (%s)' % exc)
    return r


#: `meta` key set when the user DISMISSES a recovered container's "Scene not
#: recovered" notice (#547, `set_notice <set>, 1`). Not written when the notice is
#: shown, nor when a staging action clears it: staging and then crashing again before
#: a save is the same dead end, and the next Open must say so again (review round 1).
#: The trigger itself already requires a session-less open.
RECOVERY_NOTICE_KEY = 'recovery_notice'

#: `meta` key naming the set the drawer was last opened on -- "the most recently
#: active set" a recovery points at. Written by `appkit_sets.open_set`.
LAST_ACTIVE_KEY = 'last_active_set'

RECOVERY_TEXT = 'Scene not recovered.'


def most_recently_active_set(c):
    """The set the user was last working in: the one the drawer was last opened on,
    else the one that received the newest entry, else the newest set. None when the
    file has no sets."""
    sets = c.sets()
    if not sets:
        return None
    by_id = {s['id']: s for s in sets}
    last = c.meta_get(LAST_ACTIVE_KEY, '') or ''
    if last in by_id:
        return by_id[last]
    newest = None
    for s in sets:
        rows = c.entries(s['id'], order_by='e.created DESC', limit=1)
        stamp = rows[0]['created'] if rows else s.get('created') or 0
        if newest is None or stamp > newest[0]:
            newest = (stamp, s)
    return newest[1]


def after_recovery(_self=cmd):
    """A recovered container was opened and the scene did not come back with it
    (#547): the sets, stars and views are there, and nothing is staged. Put a notice
    on the most recently active set -- the drawer draws it as `Scene not recovered.
    [Stage N starred] [Apply <view>] [Dismiss]` -- open the drawer on that set, and
    say the same on the console, with the command, for an agent or a user without
    the drawer. Not after an explicit Dismiss (`RECOVERY_NOTICE_KEY`). Returns the set's name, or '' when there was nothing to point at."""
    c = container()
    if c.meta_get(RECOVERY_NOTICE_KEY):
        return ''
    row = most_recently_active_set(c)
    if row is None:
        return ''
    c.set_notice(row['id'], {'kind': 'recovered', 'text': RECOVERY_TEXT})
    try:
        from pymol import appkit_sets
        appkit_sets.open_set(row['name'], _self=_self)
    except Exception:
        pass
    # The same entries the drawer's "Stage N starred" counts, and the same cut to the
    # budget its "Stage top K starred" makes.
    starred = stageable_starred(c, row)
    views = c.views(row['id'])
    hints = []
    if starred:
        chosen, label = pick_to_fit(c, row, starred, _self=_self)
        if len(chosen) == len(starred):
            hints.append('"set_stage %s, starred" puts its %d starred entr%s back'
                         % (row['name'], len(starred), 'y' if len(starred) == 1 else 'ies'))
        elif chosen:
            hints.append('"set_stage %s, %s" stages the top %d of its %d starred entries'
                         ' (%s; the budget is %d)'
                         % (row['name'], '+'.join(e['name'] for e in chosen), len(chosen),
                            len(starred), 'by %s' % label if label else 'in delivery order',
                            budget(row)))
        else:
            hints.append('its %d starred entries do not fit the stage budget (%d);'
                         ' unstage some or raise it with set_budget'
                         % (len(starred), budget(row)))
    if views:
        # What the drawer's "Apply <view>" does: the view's filter and sort become the
        # set's. Not `set_stage ..., view:`, which would usually be over budget.
        view = views[-1]
        steps = ['"set_filter %s, %s"' % (row['name'], view['filter'])
                 if view.get('filter') else '"set_filter %s"' % row['name']]
        if view.get('sort_key'):
            steps.append('"set_sort %s, %s, %d"' % (row['name'], view['sort_key'],
                                                     int(view.get('sort_desc', 1))))
        hints.append('its view %s applies with %s' % (view['name'], ' and '.join(steps)))
    colorprinting.parrot(' sets: %s -- the sets came back, the scene did not.%s'
                         % (row['name'], (' ' + '; '.join(hints) + '.') if hints else ''))
    return row['name']
