#!/usr/bin/env python3
"""Render the materials gallery headlessly with a built RayMol.app (#500).

    python3 scripts/materials_gallery/render.py --app /path/RayMol-dev.app \\
        --out /tmp/materials-gallery [--only surface,cartoon] [--lock-check]

Then build the page:

    python3 scripts/materials_gallery/gallery.py /tmp/materials-gallery

Every image is one `open -n` of the app with PYMOL_AUTOCMD running a scene
script and PYMOL_AUTOEXPORT writing the PNG. Three things this has to get right,
each learnt the hard way:

  * The material is BAKED INTO the generated scene script. `open -n --env`
    forwards only the variables it is given, so a scene that read the material
    from the environment silently rendered `default` every time.
  * The app must have its OWN CFBundleIdentifier. Sharing io.raymol.RayMol with
    a RayMol the user has open makes every headless instance start, sit idle
    and never render -- no crash, no log. render.py refuses that bundle id.
  * The FIRST export after a fresh copy of the app is staged renders
    differently (first-launch work shifts how far the surface has built when
    the export fires). render.py renders one throwaway image first.

Standard library only. No setting in the scene is read from the environment.
"""
import argparse
import json
import os
import plistlib
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, os.pardir, os.pardir))

SCENE = '''# generated by scripts/materials_gallery/render.py -- do not edit
from pymol import cmd, util
cmd.reinitialize()
cmd.load({pdb!r}, "m")
cmd.remove("solvent or hetatm")
cmd.hide("everything")
cmd.show({show_rep!r}, {show_sel!r})
{colour}
{extra}
cmd.set({setting!r}, {material!r}, "m")
cmd.set("bg_rgb", {bg!r})
cmd.set("depth_cue", 0)
cmd.set("ray_opaque_background", 1)
cmd.set("metal_dof", 0)
cmd.set("metal_temporal_ao", 0)
cmd.orient("m")
{view}
'''


def bundle_id(app):
    with open(os.path.join(app, 'Contents', 'Info.plist'), 'rb') as handle:
        info = plistlib.load(handle)
    return info['CFBundleIdentifier'], info['CFBundleExecutable']


def scene_script(manifest, rep, material, bg, view_lines=()):
    spec = manifest['reps'][rep]
    return SCENE.format(
        pdb=os.path.join(ROOT, manifest['structure']),
        show_rep=spec['show'][0], show_sel=spec['show'][1],
        colour='\n'.join(spec['colour']), extra='\n'.join(spec['extra']),
        setting=spec['setting'], material=material,
        bg=manifest['backgrounds'][bg], view='\n'.join(view_lines))


def export(app, exe, script_path, png, size, rt, timeout=120):
    if os.path.exists(png):
        os.remove(png)
    env = ['--env', 'PYMOL_SKIP_WHATS_NEW=1',
           '--env', 'PYMOL_AUTOCMD=run %s' % script_path,
           '--env', 'PYMOL_AUTOEXPORT=%s,%d,%d,%d' % (png, size[0], size[1], rt)]
    subprocess.run(['open', '-n'] + env + [app], check=True)
    binary = os.path.join(app, 'Contents', 'MacOS', exe)
    try:
        for _ in range(timeout):
            if os.path.exists(png) and os.path.getsize(png) > 0:
                time.sleep(2)   # let the writer finish
                return True
            time.sleep(1)
        return False
    finally:
        subprocess.run(['pkill', '-f', binary])
        time.sleep(1)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--app', required=True, help='a RayMol .app with its own bundle id')
    ap.add_argument('--out', required=True)
    ap.add_argument('--only', default='', help='comma-separated reps')
    ap.add_argument('--materials', default='', help='comma-separated subset')
    ap.add_argument('--lock-check', action='store_true',
                    help='render the pan pairs for the pattern-lock check too')
    args = ap.parse_args()

    # PyMOL's `run` takes the path unquoted (quoting it makes the scene
    # silently not run -- every image comes out blank), so a path with
    # whitespace cannot be passed through PYMOL_AUTOCMD at all. Refuse it.
    for label, path in (('--out', os.path.abspath(args.out)), ('checkout', ROOT)):
        if any(c.isspace() for c in path):
            sys.exit('%s path %r contains whitespace, which PYMOL_AUTOCMD '
                     'cannot carry; use a path without spaces' % (label, path))
    manifest = json.load(open(os.path.join(HERE, 'manifest.json')))
    ident, exe = bundle_id(args.app)
    if ident == 'io.raymol.RayMol':
        sys.exit('refusing %s: give the copy its own CFBundleIdentifier '
                 '(see the docstring)' % args.app)
    os.makedirs(os.path.join(args.out, 'scenes'), exist_ok=True)
    size = manifest['size']
    reps = [r for r in manifest['reps'] if not args.only or r in args.only.split(',')]
    mats = [m for m in manifest['materials']
            if not args.materials or m in args.materials.split(',')]

    jobs = []   # (tag, script text, rt)
    for rep in reps:
        for bg in manifest['backgrounds']:
            for rtname, rt in manifest['raytrace'].items():
                for mat in mats:
                    tag = '%s_%s_%s_%s' % (rep, bg, rtname, mat)
                    jobs.append((tag, scene_script(manifest, rep, mat, bg), rt))
    if args.lock_check:
        lc = manifest['lock_check']
        for rep in lc['reps']:
            for mat in lc['materials']:
                for i, dx in enumerate((0.0, lc['pan_angstrom'])):
                    lines = ['cmd.set("orthoscopic", 1)',
                             'cmd.move("x", %r)' % dx]
                    tag = 'lock_%s_%s_%d' % (rep, mat, i)
                    jobs.append((tag, scene_script(manifest, rep, mat, 'light',
                                                   lines), 0))

    if not jobs:
        sys.exit('nothing to render: --only/--materials matched nothing')
    # One throwaway render: the first launch of a freshly staged copy differs.
    warm = os.path.join(args.out, 'scenes', '_warm.py')
    open(warm, 'w').write(jobs[0][1])
    export(args.app, exe, warm, os.path.join(args.out, '_warm.png'), size, 0)

    failed = []
    for n, (tag, text, rt) in enumerate(jobs, 1):
        script = os.path.join(args.out, 'scenes', tag + '.py')
        open(script, 'w').write(text)
        png = os.path.join(args.out, tag + '.png')
        ok = export(args.app, exe, script, png, size, rt)
        # A scene that never ran still exports: a blank frame of a few KB.
        # The smallest real render here is ~40 KB (clear glass sticks).
        if ok and os.path.getsize(png) < 20000:
            ok = False
        print('[%d/%d] %s %s' % (n, len(jobs), tag,
                                 'ok' if ok else 'NO OUTPUT OR BLANK'),
              flush=True)
        if not ok:
            failed.append(tag)
    # The manifest gallery.py reads is the one that was RENDERED: a subset run
    # (--only / --materials) must not be judged against cells it never drew.
    rendered = dict(manifest)
    rendered['reps'] = {r: manifest['reps'][r] for r in reps}
    rendered['materials'] = mats
    if not args.lock_check:
        rendered['lock_check'] = dict(manifest['lock_check'], reps=[])
    else:
        # every lock material is rendered whatever --materials says; only
        # the representation filter applies to the lock pairs
        rendered['lock_check'] = dict(manifest['lock_check'],
            reps=[r for r in manifest['lock_check']['reps'] if r in reps])
    with open(os.path.join(args.out, 'manifest.json'), 'w') as handle:
        json.dump(rendered, handle, indent=2)
    if failed:
        sys.exit('%d renders produced nothing: %s' % (len(failed), ', '.join(failed)))


if __name__ == '__main__':
    main()
